### ISSUE TITLE
[Bug]: Unable to resize the text boxes in extensions

### ISSUE THREAD

**Issue by derrian-distro** [anapnoe/stable-diffusion-webui-ux#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When using extensions such as WD1.4 tagger or the dataset tag editor, the text boxes which display the tags are locked to being only 1 line. This means that the tags, which usually takes up more than one line is impossible to read unless you copy and paste it elsewhere. It would be nice if there is a way to resize the text box or if it automatically resized according to the text added to it as it makes doing my normal tagging for LoRA I make nearly impossible to do. This issue also directly impacts looking at metadata for additional networks, as all of the metadata boxes are these types of text boxes. 

### Steps to reproduce the problem

1. Have any of the above mentioned extensions installed
2. activate or use the extension like usual, in this case WD1.4 tagger
3. Run the tagger, and wait for results
4. see that the tag box does not expand to show all tags
tagger:
![tagger](https://user-images.githubusercontent.com/121591654/235207847-c5b6af02-2a12-4d6e-821c-87def8752715.png)
dataset tag manager:
![dataset tag manager](https://user-images.githubusercontent.com/121591654/235208241-21eecbd1-4069-4eb7-94db-83332af0508d.png)
additional networks metadata tab:
![additional networks metadata tab](https://user-images.githubusercontent.com/121591654/235208468-c2dd3614-0888-4ffa-9012-95beb82ac496.png)

### What should have happened?

The text boxes expand to fit the text, or have a way to be resized so that the user can see all of the elements/tags

### Commit where the problem happens

6fbe525f

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--opt-sdp-attention
```

### List of extensions

- a1111-sd-webui-lycoris
- a1111-sd-webui-tagcomplete
- multidiffusion-upscaler-for-automatic1111
- sd-webui-additional-networks
- sd-webui-aspect-ratio-helper
- sd-webui-controlnet
- sd-webui-lora-block-weight
- sd-webui-regional-prompter
- stable-diffusion-webui-dataset-tag-editor
- stable-diffusion-webui-wd14-tagger

### Console logs

```Shell
No error, it still works as intended, however doesn't resize to fit the new text
```

**Comment by SoftwareGuy** [comment]
Can confirm that this issue also occurs in a Firefox-based web browser like Waterfox. You have to manually resort to CSS hacks via the Web Inspector by forcing an override of the heigh value.

This is an oversight because I strongly doubt anyone with a high resolution monitor (1080 upwards) would want to try to copy all the text from a one-line-high field.

Please look into fixing the template for this to be rectified.

**Comment by anapnoe** [comment]
if you click inside the tag field does it expand? I have added this functionality for all textarea fields, if defined as textarea type by extension

**Comment by derrian-distro** [comment]
you can only do so for text areas that allow editing. Clicking does not do anything when the textarea is not editable. I looked at the code, and yes for all cases, they are textarea. It might be helpful to have it detect when text is programmatically added and expand to match that text, as when text is added to a textarea that is not editable, there is no way to resize it.

**Comment by anapnoe** [comment]
don't want to add an observer for this as textarea components exist everywhere in the ui settings, extensions etc
I will attach the onfocus listener to the parent element of the textarea as you pointed out if the component is disabled the event is not triggered
