### ISSUE TITLE
[Feature Request]: Lazy-load extra network thumbnails?

### ISSUE THREAD

**Issue by midcoastal** [anapnoe/stable-diffusion-webui-ux#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Just...  Don't load the thumbnails until the tab is expanded.  

In an ideal world this would mean we don't load the network type thumbnails until that network type is visible, but if that is too granular, just delaying loading all until the tab is expanded would be super helpful.

I have something like 3k extra networks, I'd love to reclaim 40 seconds of load time (and that is LOCALLY, from the same machine, this locks the browser for minutes if I do it remote...)

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

See above

**Comment by anapnoe** [comment]
I will do that it is in my todo list
