### ISSUE TITLE
[Bug?]: Large number of models causes things to start breaking...

### ISSUE THREAD

**Issue by midcoastal** [anapnoe/stable-diffusion-webui-ux#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Well, first-off, load times go crazy loading all the preview thumbnails.

But most importantly, after a few renders, you can't render any more.  

Additionally: Moving images to things like `img2img` stops working, and the token counter just jams up and dies (indicator stays lit, and the text box is masked [this is a problem, btw, it prevents the cursor from selecting the text box, bad juju]).

### Steps to reproduce the problem

1. Have four-thousand models of various types (I wish I were kidding).
2. Load it up, and render a thing.
3. Try again, and get aaaannnngerrrr

### What should have happened?

Kept working, I don't know.

Not exactly sure why the number of models you have should matter at any given time, unless you are interacting with them, which, sure.

### Commit where the problem happens

6fbe525f7dafd63b447334b6c476c190b02da7cb

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --listen --api --disable-nan-check --no-hashing --enable-insecure-extension-access --embeddings-dir X:\\...\\stable-diffusion-webui\\models\\embeddings --xformers
```

### List of extensions

Just built-in when reproducing.

### Console logs

```Shell
No errors when this occurs
```

**Comment by midcoastal** [comment]
Well isn't that egg on my face...  I didn't actually have all extensions off.  Just turned all but LDSR, Lora, ScuNET, and SwinIR, off, and the problem didn't recur.  Slowly turning extensions on, we'll see.

**Comment by anapnoe** [comment]
you can post which extension caused the issue for other people to know

**Comment by midcoastal** [comment]
A little quick to close.  I wouldn't say we are out of the woods.  I still get the issue with prompt box(es) becoming unusable.

**Comment by anapnoe** [comment]
did you upgrade to the latest commit?

**Comment by midcoastal** [comment]
> did you upgrade to the latest commit?

Trying now

**Comment by midcoastal** [comment]
> did you upgrade to the latest commit?

Whelp, I think you may have gone and done it.  Looks like things lazy-load now, which is AWESOME, and so far I can't get it to hose the UI.  So, awesome!  THanks!
