### ISSUE TITLE
[Bug]:  Inpainting completely broken

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When you attempt to send any image to inpainting, it loads up on canvas but when you press generate. it locks up the console terminal. nothing happens in the console. and it locks up the WebUI browser unable to navigate. if you close the browser and reopen you can generate images in text2image, but as soon as you generate inside inpaint it locks up again. Also the movement on the canvas feels like it's at like 5-10fps

### Steps to reproduce the problem

Generate any image, send to inpaint, draw on inpaint press generate and it locks up.

### What should have happened?

It should inpaint.

### Commit where the problem happens

e2d23b4

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae --autolaunch
```

### List of extensions

built in only. tested on completely new git clone and clean install.

### Console logs

```Shell
Console locks up nothing interesting
```

### Additional information

https://imgur.com/a/eRVk6cP

**Comment by rushuna86** [comment]
did checkout to 9fc075e and everything works again. so it's most likely the automatic 1111 update to 1.10

**Comment by anapnoe** [comment]
gradio bump to 3.28.1 didn't help much it seems slower to me too I will investigate more thanks

**Comment by anapnoe** [comment]
remove --api from the command args and it will work as expected
