### ISSUE TITLE
[Feature Request]: Static Hamburger Menu Option. 

### ISSUE THREAD

**Issue by holymode** [anapnoe/stable-diffusion-webui-ux#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

It would be nice to have a setting to change how the hamburger menu on the left side behaves. Right now its very.. suboptimal. If you generate pictures and want to change to img2img or any other extensions, it requires opening it. If you're a heavy user it gets very annoying to click and wait until the menu appears and clicking again for the extension. 

It would be nice to have it either like [this](https://i.imgur.com/UIbfGf2.png) or with symbols. Or on the left side have the menu static, either displaying some short text or symbols. 

First method would be nice. Like in the original versions. 

### Proposed workflow

1. Go to settings menu or style menu
2. Press the style you want.
3. Profit

**Comment by anapnoe** [comment]
it is already implemented search for header tabs in the settings add it to quicksettings to have it available so you can customize your workflow as you wish on the fly
