### ISSUE TITLE
[Feature Request]: Hide theme menu in Settings

### ISSUE THREAD

**Issue by ghostsquad** [anapnoe/stable-diffusion-webui-ux#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

This is a suggestion to hide the theme modifier menu in left hand sandwich menu or settings menu.

![image](https://user-images.githubusercontent.com/903488/236342901-666b0049-0ac8-417c-9d59-0adfc590652b.png)

It shouldn't really be something that is often used, which means I don't want it up front.

### Proposed workflow

N/A

**Comment by anapnoe** [comment]
open extentions uncheck sd_theme_editor reload ui

**Comment by ghostsquad** [comment]
Thank you very much!
