### ISSUE TITLE
[Bug]: Generation/Magic Wand, Load Preset Button doesnt work sometimes

### ISSUE THREAD

**Issue by holymode** [anapnoe/stable-diffusion-webui-ux#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

My friend is hosting sd on his computer, when I try to use the hosted version the button for loading last generation info doesn't work. The field gets locked up with the dot. You can still type, but you can never load any other presets. Sometimes the generation button works, but other times this also won't work anymore. 
The weird issue is, sometimes all buttons work fine and after some minutes it starts to break. Only a refresh with clearing cookie allows it to work again. 

In the commit 787bd399 everything works fine on my site. I believe it might be some issue with the new gradio version. 

There are no error logs, no 404 in dev tools. 

Note; I wrote test after clicking the magic wand button, thats not the old generation info
![image (6)](https://user-images.githubusercontent.com/59067594/236357222-b6dc62e3-bca4-43ea-bd38-3f84047b1653.png)

Here is another picture showing that it is just loading but never finishing. 

![image (7)](https://user-images.githubusercontent.com/59067594/236357506-04897f2b-7f7f-412a-a352-4c8a72fe84ec.png)

This issue is similar https://github.com/anapnoe/stable-diffusion-webui-ux/issues/109

### Steps to reproduce the problem

1. Open site
2. Press read generation parameter button / or try to load any preset
3. The dot will show up and will never go away. 
4. Try to type prompt and click generate
5. It will either work fine or it will show "waiting" and then just never complete. 

### What should have happened?

Buttons should work fine without any issue, no matter where the user connects from. 

### Commit where the problem happens

5ab7f21

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
COMMANDLINE_ARGS=--api --disable-safe-unpickle --opt-sdp-attention --enable-insecure-extension-access --no-download-sd-model --no-half-vae --disable-console-progressbars --listen --api-auth xxxx:xxxxxx,xxx:xxxxxxxxx --gradio-auth xxxx:xxxxxx,xxx:xxxxxxxxx --port 7860 --api-log --opt-split-attention-v1
```

### List of extensions

![2023-05-05_02-42](https://user-images.githubusercontent.com/59067594/236357836-60275f26-4362-4909-af67-06d214e60da1.png)

### Console logs

```Shell
Installing requirements for Web UI


Installing requirements 1 for Infinite-Zoom



Installing sd-dynamic-prompts requirements.txt




Launching Web UI with arguments: --api --disable-safe-unpickle --opt-sdp-attention --enable-insecure-extension-access --no-download-sd-model --no-half-vae --disable-console-progressbars --listen --api-auth xxxx:xxxxxx,xxx:xxxxxxxxx --gradio-auth xxxx:xxxxxx,xxx:xxxxxxxxx --port 7860 --api-log --opt-split-attention-v1
No module 'xformers'. Proceeding without it.
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
```

**Comment by anapnoe** [comment]
can you update to latest commit?

**Comment by anapnoe** [comment]
thank you yes it would be useful for other people you can report this to the extension author to fix it
