### ISSUE TITLE
[Bug]: Hidden Tabs settings not working

### ISSUE THREAD

**Issue by midcoastal** [anapnoe/stable-diffusion-webui-ux#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Two Bugs:

Hidden Tabs not respected:  I have `Hidden Tabs` settings from back when I was using base Auto, and they are not respected when running the UX version (the tabs still display when I use the hamburg menu).

Hidden Tabs Selector not working:  Perhaps unsurprisingly, when I went to try to re-configure the hidden tabs, to see if that would resolve the issue, the "Auto Complete" feature, and the Dropdown selector did not work, making the feature useless all around.  :-(

### Steps to reproduce the problem

1. Go to Settings, User Interface
2. Try to change Hidden Tabs
3. Rage Quit

### What should have happened?

The Hidden Tabs input should have a populated dropdown list, as well as auto-complete while you type.

Further, if you have tabs identified already (from a previous install), they should not show up in the hamburg menu.

### Commit where the problem happens

780ef776032675bda53cdc5f0e8be3341a08a5cf

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --api --disable-nan-check --no-hashing --enable-insecure-extension-access --xformers
```

### List of extensions

No

### Console logs

```Shell
none regarding this issue
```

**Comment by midcoastal** [comment]
I'm a fool, I see there are two hidden tabs areas?  That is odd...

I had `Hidden UI tabs (requires restart)` configured before, but I see there is an option just `Hidden Tabs`.

Follow up question:  Why are there two?

**Comment by anapnoe** [comment]
Hidden UI Tabs(requires restart) is the implementation from the original repo
while the other is the ui-ux implementation that works in parallel with hidden tabs and doesn't require restart
I forgot to remove it from the shared.py as it does nothing 
sorry for the confusion
