### ISSUE TITLE
[Bug]: Fail on --no-gradio-queue

### ISSUE THREAD

**Issue by midcoastal** [anapnoe/stable-diffusion-webui-ux#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I am opening up SD to some friends.  This is my personal PC, so I am passing it through an `nginx` proxy, and I have determined that sockets are not behaving correctly through this proxy.  As such, I want to disable the Gradio Queue, but this prevents the app from running.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

Just add `--no-gradio-queue` to `COMMANDLINE_ARGS`

### What should have happened?

The app should launch without the queue just fine

### Commit where the problem happens

6fbe525f7dafd63b447334b6c476c190b02da7cb

### What platforms do you use to access the UI ?

Windows

### Command Line Arguments

```Shell
--opt-sdp-attention --listen --api --disable-nan-check --no-hashing --xformers --skip-install --hide-ui-dir-config --no-gradio-queue
```

### List of extensions

None of consequence

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\...\launch.py", line 356, in <module>
    start()
  File "D:\...\launch.py", line 351, in start
    webui.webui()
  File "D:\...\webui.py", line 316, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\...\venv\lib\site-packages\gradio\blocks.py", line 1687, in launch
    self.validate_queue_settings()
  File "D:\...\venv\lib\site-packages\gradio\blocks.py", line 1541, in validate_queue_settings
    raise ValueError("Progress tracking requires queuing to be enabled.")
ValueError: Progress tracking requires queuing to be enabled.
Press any key to continue . . .
```

**Comment by anapnoe** [comment]
you need to go to settings and disable progressbar as Progress tracking requires queuing to be enabled.
