### ISSUE TITLE
[Bug]: Cannot open long click menu or copy-paste options in mobile.

### ISSUE THREAD

**Issue by pseudokawaii** [anapnoe/stable-diffusion-webui-ux#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I cannot seem to open the long-press menu or copy-paste menu after updating to the latest commit. Which i was able to before the update.

### Steps to reproduce the problem

1. Open the latest webui in Google Chrome mobile.
2. Long press any text to open the copy-paste menu.
3. Or generate an image then try to open the long-press context menu by long pressing on the image.

### What should have happened?

Should've been able to open the copy-paste menu or long-press context menu without any issues.

### Commit where the problem happens

0eb1529

### What platforms do you use to access the UI ?

Android

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
python launch.py --enable-insecure-extension-access --disable-safe-unpickle --opt-sdp-attention --no-hashing --disable-console-progressbars --opt-sub-quad-attention --opt-channelslast --theme=dark --no-download-sd-model --gradio-queue --listen --port 8000 --lowram --no-half-vae
```

### List of extensions

`a1111-sd-webui-locon`
`a1111-sd-webui-lycoris`
`a1111-sd-webui-tagcomplete`
`batchlinks-webui`
`booru2prompt`
`sd-webui-additional-networks`
`sd-webui-ar`
`sd-webui-controlnet`
`sd-webui-lora-block-weight`
`stable-diffusion-webui-images-browser`
`ultimate-upscale-for-automatic1111`

### Console logs

```Shell
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]
Commit hash: 7c64783bbcfccebd8b9950a1b0a010b4d9afc96e
Installing gfpgan
Installing clip
Installing open_clip
Installing requirements for CodeFormer
Installing requirements


Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: fvcore

Launching Web UI with arguments: --enable-insecure-extension-access --disable-safe-unpickle --opt-sdp-attention --share --no-hashing --disable-console-progressbars --opt-sub-quad-attention --opt-channelslast --theme=dark --no-download-sd-model --gradio-queue --listen --port=8000 --lowram --no-half-vae
No module 'xformers'. Proceeding without it.
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading booru2prompt settings
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
ControlNet v1.1.150
ControlNet v1.1.150
Image Browser: ImageReward is not installed, cannot be used.
Loading weights [None] from /home/jovyan/workspace/sd-webui/models/Stable-diffusion/perfectWorld_v3Baked.safetensors
Creating model from config: /home/jovyan/workspace/sd-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /home/jovyan/workspace/sd-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(16): bad-hands-5, bad-picture-chill-75v, bad_prompt_version2-neg, dld_selgomez, easynegative, koh_miakhalifa, negative_hand-neg, ng_deepnegative_v1_75t, pureerosface_v1, realcumAI, realisticvision-negative-embedding, selenagomez, sleoe69, ulzzang-6500-v1.1, Unspeakable-Horrors-Composition-4v, verybadimagenegative_v1.3
Model loaded in 46.0s (load weights from disk: 41.4s, create model: 2.9s, load VAE: 1.6s).
Running on local URL:  http://0.0.0.0:8000
Running on public URL: https://e2623d55fa2dbd192c.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Startup time: 62.9s (import torch: 1.6s, import gradio: 3.7s, import ldm: 0.4s, other imports: 2.3s, setup codeformer: 0.1s, load scripts: 1.6s, load SD checkpoint: 46.0s, create ui: 3.4s, gradio launch: 3.7s).
locon load lora method
100%|███████████████████████████████████████████| 25/25 [00:10<00:00,  2.45it/s]
100%|███████████████████████████████████████████| 25/25 [00:51<00:00,  2.05s/it]
```
```


### Additional information

The issue gets solved if i revert to commit https://github.com/anapnoe/stable-diffusion-webui-ux/commit/7c64783bbcfccebd8b9950a1b0a010b4d9afc96e.

**Comment by anapnoe** [comment]
You can disable the `Dispatch event change on release, for slider and input number components` in the User Interface Settings for now, I will fix it I suppress the context menu event for the long press I will remove the listener

**Comment by anapnoe** [comment]
can you test if it has been fixed with the `Dispatch event change on release, for slider and input number components` enabled that is improving responsiveness for mobile remove the context menu listener for long press

**Comment by pseudokawaii** [comment]
> can you test if this has been fixed with the `Dispatch event change on release, for slider and input number components` enabled that is improving responsiveness for mobile?

Yes, i just tested with the latest commit and it's working perfectly after disabling the `Dispatch event change on release, for slider and input number components` from User Interface settings.
