### ISSUE TITLE
[Bug]: additional networks does not list any models

### ISSUE THREAD

**Issue by halr9000** [anapnoe/stable-diffusion-webui-ux#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Networks are gone:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/c88409c8-9f2e-43a7-85b5-d4fa45307282)

### Steps to reproduce the problem

1. Start webui
2. click additional networks button
3. no networks are shown

Have tried  
* multiple devices and browsers
* disabling recent extensions (by memory, possible I missed some)
* restarted process/terminal
* ctrl-F5 hard refresh
* incognito mode

### What should have happened?

Should see TI, Checkpoints, Lora etc

### Commit where the problem happens

9aba26abdfcd46073e0a1d42027a3a3bcc969f562d58a03637bf0a0ded6586c9

### What platforms do you use to access the UI ?

Windows, iOS, Android

### What browsers do you use to access the UI ?

Google Chrome, Apple Safari

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--listen --enable-insecure-extension-access --no-half --api --xformers --update-all-extensions --ckpt-dir="D:\hal\stable-diffusion\models\Stable-diffusion" --lora-dir="D:\hal\stable-diffusion\models\Lora" --embeddings-dir="D:\hal\stable-diffusion\models\Embeddings" --hypernetwork-dir="D:\hal\stable-diffusion\models\Hypernetworks"
```

### List of extensions

a1111-sd-webui-locon
a1111-sd-webui-lycoris
a1111-sd-webui-tagcomplete
depthmap2mask
multidiffusion-upscaler-for-automatic1111
OneButtonPrompt
sd-canvas-editor
sd-dynamic-prompts
sd-extension-system-info
sd-webui-3d-open-pose-editor
sd-webui-ar
sd-webui-aspect-ratio-helper
sd-webui-controlnet
sd-webui-enable-checker
sd-webui-infinite-image-browsing
sd-webui-inpaint-anything
sd-webui-regional-prompter
sd-webui-segment-anything
Stable-Diffusion-Webui-Civitai-Helper
stable-diffusion-webui-composable-lora
stable-diffusion-webui-nsfw-censor
stable-diffusion-webui-promptgen
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
I see no errors. :( 

Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --api --xformers --update-all-extensions --ckpt-dir=D:\hal\stable-diffusion\models\Stable-diffusion --lora-dir=D:\hal\stable-diffusion\models\Lora --embeddings-dir=D:\hal\stable-diffusion\models\Embeddings --hypernetwork-dir=D:\hal\stable-diffusion\models\Hypernetworks
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\hal\stable-diffusion\ux\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading weights [9aba26abdf] from D:\hal\stable-diffusion\models\Stable-diffusion\sd15\deliberate_v2.safetensors
Creating model from config: D:\hal\stable-diffusion\ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(32): 16-token-negative-deliberate-neg, AS-Young, AS-Young-neg, AS-Younger, AS-Youngest, Bsft, dangerdonkey, easynegative, fractal-flame, gothbuilding, hobbithouse, hobbithouse_2, hrgiger-drmacabre, Isometric_Dreams, kc16-4000-sd1-5, kkw-micro, ng_deepnegative_v1_64t, photozoov15, Planit, qualityzoov15, renderzoov15, structurezoov15, Style-Glass, Style-Info, style-paintmagic, Style-Psycho, Style-Renaissance, style-rustmagic, Style-Winter, vintagemap_f, was-dieselpunk, was-mecha
Textual inversion embeddings skipped(10): dangerhorse, Neg_Facelift768, nfixer, nrealfixer, photozoov21, DrD_PNTE768, Painted_Landscape, ParchArt, Davespacefour, Knollingcase
Model loaded in 3.2s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 0.7s, move model to device: 1.1s, load textual inversion embeddings: 0.9s).
ControlNet v1.1.170
ControlNet v1.1.170
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.6s (import torch: 2.2s, import gradio: 1.1s, import ldm: 0.6s, other imports: 0.9s, load scripts: 6.5s, create ui: 3.8s, gradio launch: 4.3s).
```

### Additional information

Checked js console, nothing helpful there either.

**Comment by anapnoe** [comment]
can you check if it is ok now?

**Comment by halr9000** [comment]
> can you check if it is ok now?

Interesting, its failing to load due to bad settings detected, which I've never seen before. See if I can fix this, will report back.

```
Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --api --xformers --update-all-extensions --ckpt-dir=D:\hal\stable-diffusion\models\Stable-diffusion --lora-dir=D:\hal\stable-diffusion\models\Lora --embeddings-dir=D:\hal\stable-diffusion\models\Embeddings --hypernetwork-dir=D:\hal\stable-diffusion\models\Hypernetworks
Warning: bad setting value: quicksettings: sd_model_checkpoint,ui_header_tabs,outdir_samples,samples_save (str; expected list)
The program is likely to not work with bad settings.
Settings file: D:\hal\stable-diffusion\ux\config.json
Either fix the file, or delete it and restart.
<snip stuff about models loading etc>
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\ux\launch.py", line 370, in <module>
    start()
  File "D:\hal\stable-diffusion\ux\launch.py", line 365, in start
    webui.webui()
  File "D:\hal\stable-diffusion\ux\webui.py", line 295, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\hal\stable-diffusion\ux\modules\ui.py", line 1660, in create_ui
    component = create_setting_component(k, elem_id)
  File "D:\hal\stable-diffusion\ux\modules\ui.py", line 1551, in create_setting_component
    raise Exception(f'bad options item type: {t} for key {key}')
Exception: bad options item type: <class 'list'> for key quicksettings
```

**Comment by halr9000** [comment]
Turned the str into a list, that resolved the first error, but the second fatal one was still there. 

Removed key entirely, same.

Renamed config.json out of the way, webui made a new one -- which still throws an error! Gotta revert.
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/860bf3a5-a654-4c05-809f-aee93321b2af)

**Comment by halr9000** [comment]
Reverted back to 94a759bd9f3d48be54bf4da54fa97ec637088c3f, had to rm config.json for it to start. (Should work with my backup, just haven't tried that yet.)

**Comment by anapnoe** [comment]
yes it is fixed now I did also remove the config some property cause the problem did dig in to to find which one

**Comment by halr9000** [comment]
P.S. while you are in here, can you autohide empty tabs? Lycoris does nothing. I'll make a feature request.

**Comment by anapnoe** [comment]
can you disable civitai i suspect it has something to do with this i will look into it

**Comment by Linaqruf** [comment]
Uhh, got the same problem when running it in Colab Notebook, and not only LoRA but also other model card won't load or greyed out even though it's there in the folder.

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/50163983/c2c31c4d-f046-4c41-8d2f-cf18b3eeea07)

**Comment by anapnoe** [comment]
thanks for this very helpful info I will look into this

**Comment by anapnoe** [comment]
can you confirm this is related to https://github.com/anapnoe/stable-diffusion-webui-ux/issues/148
and has been fixed?

**Comment by Linaqruf** [comment]
Thank you for the fix, but I think my issue is different from https://github.com/anapnoe/stable-diffusion-webui-ux/issues/148, because it hasn't been fixed on my side. Extra network menu still greyed out and can't load the card.

I'm using https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3 right now and the extra network menu is normal, unlike the latest commit

Should I create new issue for this?

Commit hash: 64715b57666d619a98b2a16504b7184cf2fc5402

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/50163983/57fe5a1a-a159-48c1-a41b-3040f52001a3)

Commit hash: f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/50163983/b0441e7e-5036-4289-a024-23fec4d97c1a)

**Comment by pseudokawaii** [comment]
It may not be a useful information but https://github.com/anapnoe/stable-diffusion-webui-ux/commit/ddd44e452ddce63c2a24c558e4b28acc620330a4 works for me without causing any major surface level issues. The only minor issue is i have to reload the extra networks tab every time for them to show up.

**Comment by anapnoe** [comment]
> Thank you for the fix, but I think my issue is different from #148, because it hasn't been fixed on my side. Extra network menu still greyed out and can't load the card.
> 
> I'm using [f2b9c2c](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3) right now and the extra network menu is normal, unlike the latest commit
> 
> Should I create new issue for this?
> 
> Commit hash: [64715b5](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/64715b57666d619a98b2a16504b7184cf2fc5402)
> 
> ![image](https://user-images.githubusercontent.com/50163983/238603906-57fe5a1a-a159-48c1-a41b-3040f52001a3.png)
> 
> Commit hash: [f2b9c2c](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3)
> 
> ![image](https://user-images.githubusercontent.com/50163983/238606700-b0441e7e-5036-4289-a024-23fec4d97c1a.png)


Commit hash: 37f3b28680ae13a377f3838ed482fc9c24835483
latest I see no issue 
![Untitled](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/403a31ca-4cd5-4479-82c1-7e2098277ab9)
![Untitledi](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/ac877fb1-c46a-4ddd-9c29-592d45a30d8e)

**Comment by mart-hill** [comment]
Ah, so that's why I didn't see any finalized image after generation as of late - I redirected the whole output folder to a HDD with junction (symlink).

**Comment by pseudokawaii** [comment]
> > Thank you for the fix, but I think my issue is different from #148, because it hasn't been fixed on my side. Extra network menu still greyed out and can't load the card.
> > I'm using [f2b9c2c](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3) right now and the extra network menu is normal, unlike the latest commit
> > Should I create new issue for this?
> > Commit hash: [64715b5](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/64715b57666d619a98b2a16504b7184cf2fc5402)
> > ![image](https://user-images.githubusercontent.com/50163983/238603906-57fe5a1a-a159-48c1-a41b-3040f52001a3.png)
> > Commit hash: [f2b9c2c](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3)
> > ![image](https://user-images.githubusercontent.com/50163983/238606700-b0441e7e-5036-4289-a024-23fec4d97c1a.png)
> 
> Commit hash: [37f3b28](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/37f3b28680ae13a377f3838ed482fc9c24835483) latest I see no issue ![Untitled](https://user-images.githubusercontent.com/124302297/238705737-403a31ca-4cd5-4479-82c1-7e2098277ab9.png) ![Untitledi](https://user-images.githubusercontent.com/124302297/238705743-ac877fb1-c46a-4ddd-9c29-592d45a30d8e.png)

![Screenshot_20230517-015822_Chrome](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/63403140/c7090142-eede-4355-a6c8-a3004f92979c)
Commit https://github.com/anapnoe/stable-diffusion-webui-ux/commit/37f3b28680ae13a377f3838ed482fc9c24835483 and it's still greyed out for me too.

**Comment by Linaqruf** [comment]
> > Thank you for the fix, but I think my issue is different from #148, because it hasn't been fixed on my side. Extra network menu still greyed out and can't load the card.
> > I'm using [f2b9c2c](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3) right now and the extra network menu is normal, unlike the latest commit
> > Should I create new issue for this?
> > Commit hash: [64715b5](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/64715b57666d619a98b2a16504b7184cf2fc5402)
> > ![image](https://user-images.githubusercontent.com/50163983/238603906-57fe5a1a-a159-48c1-a41b-3040f52001a3.png)
> > Commit hash: [f2b9c2c](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/f2b9c2cb4fa5f0e866c1b6f84e44d12ff6653af3)
> > ![image](https://user-images.githubusercontent.com/50163983/238606700-b0441e7e-5036-4289-a024-23fec4d97c1a.png)
> 
> Commit hash: [37f3b28](https://github.com/anapnoe/stable-diffusion-webui-ux/commit/37f3b28680ae13a377f3838ed482fc9c24835483) latest I see no issue ![Untitled](https://user-images.githubusercontent.com/124302297/238705737-403a31ca-4cd5-4479-82c1-7e2098277ab9.png) ![Untitledi](https://user-images.githubusercontent.com/124302297/238705743-ac877fb1-c46a-4ddd-9c29-592d45a30d8e.png)

Did you launch the notebook with default setting? because I put the stable commit in `commit_hash` where the extra networks still working.

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/50163983/a0c23a71-a6e1-46bd-a841-2891b748d184)

**Comment by Linaqruf** [comment]
Oh, thank you! I think it's fixed on my side. I don't know about others. It also took some time to load the model card.

Commit hash: https://github.com/anapnoe/stable-diffusion-webui-ux/commit/37f3b28680ae13a377f3838ed482fc9c24835483

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/50163983/82689f5d-5ae7-4e1a-b8f0-46954d84c404)
