### ISSUE TITLE
[Bug]: Image disappears in Controlnet Preview Pane

### ISSUE THREAD

**Issue by zono50** [anapnoe/stable-diffusion-webui-ux#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I go to Img2Img and i put a picture in controlnet, the image tucks under the UI, and I can no longer see it.
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8764705/800df4fc-b681-4754-8cb2-4e534f704040)

I have placed an image in the box, and it tucks underneath so you can no longer see it.

### Steps to reproduce the problem

1. Go to Img2Img
2. Press controlnet, pick a picture from my computer, drag and drop onto the preview box, and it tucks down the bottom underneath the UI.
3. ...

### What should have happened?

The image should be contained in the preview box

### Commit where the problem happens

e6415c4892

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers
```

### List of extensions

Image browser
controlnet
Batch face swap
Style Pile
A111-sd-webui-locon
a1111-stable-diffusion-webui-vram-estimator
adetailer
canvas-zoom
model_preset_manager
sd-dynamic-thresholding
sd-extension-system-info
3d open pose editor
sd-webui-additional networks
sd-webui-ar
sd-webui-controlnet
sd-webui-panorama-viewer
sd-dreambooth-extension
prompt generator
webui-tokenizer
ultimate upscale

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 55.3s (import torch: 2.1s, import gradio: 0.5s, import ldm: 0.5s, other imports: 1.4s, list SD models: 0.5s, setup codeformer: 0.5s, load scripts: 41.1s, create ui: 8.3s, gradio launch: 0.3s).
Error loading embedding sxzBloom_sxzBloom.pt:
Traceback (most recent call last):
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui-ux-org/stable-diffusion-webui-ux/modules/textual_inversion/textual_inversion.py", line 210, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui-ux-org/stable-diffusion-webui-ux/modules/textual_inversion/textual_inversion.py", line 182, in load_from_file
    raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Exception: Couldn't identify sxzBloom_sxzBloom.pt as neither textual inversion embedding nor diffuser concept.

Error loading embedding sxzBloom_sxzBloom.pt:
Traceback (most recent call last):
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui-ux-org/stable-diffusion-webui-ux/modules/textual_inversion/textual_inversion.py", line 210, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui-ux-org/stable-diffusion-webui-ux/modules/textual_inversion/textual_inversion.py", line 182, in load_from_file
    raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Exception: Couldn't identify sxzBloom_sxzBloom.pt as neither textual inversion embedding nor diffuser concept.
```

### Additional information

i have two different versions of the webui on my computer. the older version doesn't have this issue from what i've seen. I can't remember the commit version of that one off the top of my head, but it was a duct taped together pip-compile version

**Comment by FutonGama** [comment]
This happen to me with some images and the resolution can't be so high also or this happen. Try use another image and a smaller to just to test it. But probably you have done that already. Another thing is canvas zoom, maybe is causing a issue and you don't need that in this fork cause you can already zoom it and i remember to use it and canvas zoom don't even worked.

**Comment by anapnoe** [comment]
remove canvas-zoom as suggested by @FutonGama it is known to cause issues 
ui-ux has inbuild zoom pan functionality

**Comment by zono50** [comment]
Yup, that was it. Removed canvas-zoom and is working as expected. Thanks

**Comment by zono50** [comment]
Removed canvas zoom, but issue still persists.

**Comment by anapnoe** [comment]
It would be nice if people try this things before post any bug
1. you should always test with the latest commit
2. disable all non inbuild extensions and test the one that causes the problem to rule out that other extension are not interfere 
3. if you use an extension update that too

so in your case it seems you are using an outdated commit
![Untitledi](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/24bbad31-836d-498a-ab1f-5324a3a7bdb8)

**Comment by zono50** [comment]
ok well if it's an issue on my end, I will close the issue then and look for a solution on my end. Thank you

**Comment by zono50** [comment]
What commit hash are you using? i'm using 37f3b28680ae13a377f3838ed482fc9c24835483 from the master branch which tells me i'm on the latest when i try to update.

**Comment by anapnoe** [comment]
yes this commit is the latest https://github.com/anapnoe/stable-diffusion-webui-ux/commit/37f3b28680ae13a377f3838ed482fc9c24835483

**Comment by zono50** [comment]
ok well i'm using the commit hash 
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8764705/452f48ef-f615-4f6f-995a-d81d08a02d05)

I disabled all my extensions except for controlnet
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8764705/9e97e63d-a71c-4070-8cc7-588b1ba9ae34)

and same thing:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8764705/099f1b90-8f6e-4fc8-b803-f83949093169)

**Comment by zono50** [comment]
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8764705/0ad35228-4a44-4c29-b72a-241d0c1db945)

Seems to work fine in the same browser but on a different commit

using manjaro with chromium

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8764705/77f68f17-7260-41f4-944c-4246335345b4)

Only thing is this older commit i'm using was duct taped together using pip-compile so it takes over 5 minutes just to load the web app

**Comment by zono50** [comment]
I tried it in firefox as well, and it's doing the same thing, so it's not a browser issue or browser extension issue either

**Comment by anapnoe** [comment]
ok drug and drop an image into the container

**Comment by zono50** [comment]
that's what i've been doing, i'll drag a file from my picture folder and drop it into the container and it tucks it neatly underneath the UI

**Comment by anapnoe** [comment]
ok the issue is strange on my end it is happening when you click to browse the same image after you have remove it 
it doesn't happen when you drop images directly to the container area

**Comment by anapnoe** [comment]
can you test it on txt2image control net drop one image then remove it and drop it again

**Comment by zono50** [comment]
On the latest commit - d6b4aebe241858efe50cda78e6738e5a978ad8c1 and did the same thing.

**Comment by zono50** [comment]
I appreciate you working on this tho.

**Comment by mart-hill** [comment]
For me, I see this after generating an image:
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/55754730/3e7b05ba-1b57-4daf-ad87-e2e2a0c6ccee)

I have the whole "outputs" folder as symlink (junction) though. I don't use canvas-zoom extension, and I can see preview rendering just fine. The image saves correctly as well.

**Comment by rushuna86** [comment]
if this issue is anything like what happened to me a while ago it is the extension "Canvas Zoom", causing i2i images to disappear. After you've installed it, it pretty much fks up the whole image2image side of thing, even disabling the extension didnt fix it. had to pull a brand new clean install and never install it to fix the issue for me.

**Comment by zono50** [comment]
I will try to reinstall it then and see what happens. Appreciate the info

**Comment by zono50** [comment]
You are 100% correct, reinstalled controlnet and auto1111 ux and works perfectly now.
