### ISSUE TITLE
Wrong installation instructions?

### ISSUE THREAD

**Issue by Hakim3i** [anapnoe/stable-diffusion-webui-ux#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Installation instruction just show how to install automatic1111 ui and not anapnoe ui the git url should be updated.

### Steps to reproduce the problem

Follow installation guide

### What should have happened?

Anapnoe UI should be installed

### Commit where the problem happens

all

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
no
```

**Comment by anapnoe** [comment]
do you want to help on this there are a ton of things yet to be done?

**Comment by Hakim3i** [comment]
> do you want to help on this there are a ton of things yet to be done?

Sir am not familiar with github but all have to be done is replacing https://github.com/AUTOMATIC1111/stable-diffusion-webui.git with https://github.com/anapnoe/stable-diffusion-webui-ux.git at least for windows.
