### ISSUE TITLE
[Bug]: Image blinking while applying hires fix.

### ISSUE THREAD

**Issue by Dajova** [anapnoe/stable-diffusion-webui-ux#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

The preview image is blinking constantly when it's applying hires fix. It seems to trigger on each and every step it completes.

### Steps to reproduce the problem

1. Prompt anything
2. Apply "highres. fix"
3. Allow it to generate until it starts applying fix.
4. Image starts to blink/flicker for each step it completes.

### What should have happened?

It should not blink when generating. At least it didnt with A1111.

### Commit where the problem happens

37f3b28

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### List of extensions

![image](https://i.imgur.com/49cWtd6.png)

### Console logs

```Shell
-
```

**Comment by anapnoe** [comment]
can not reproduce tested on Chrome and Firefox latest

**Comment by Dajova** [comment]
> can not reproduce tested on Chrome and Firefox latest

I probably forgot to mention that it's probably g-sync related, cus it sometimes goes away, but as soon as i click on another monitor, it comes back, some way or another.
