### ISSUE TITLE
[Bug]: Prompt window not adjusting to prompt size

### ISSUE THREAD

**Issue by trihardseven** [anapnoe/stable-diffusion-webui-ux#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Prompt window stops adjusting to prompt size. I think this can also happen on AUTO, but it's not a big problem there because the prompt window is larger by default. Here its one line so when it happens its a pain to keep using it, only fix is to refresh the page and possibly lose many of your settings.

<img width="833" alt="capture9" src="https://github.com/anapnoe/stable-diffusion-webui-ux/assets/54422205/2f232430-8463-48e1-91d5-d0cb47927ff3">

### Steps to reproduce the problem

1. Go to t2i
2. Write a 2+ line prompt
3. Click on the prompt dropdown and click it again
4. Now prompt text is stuck at showing 1 line only

### What should have happened?

It should show multiple lines like before

### Commit where the problem happens

2dd1a23938ee7d617728d7e09eb87480a5c586fb

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
xformers and nohalfvae
```

### List of extensions

<img width="458" alt="capture10" src="https://github.com/anapnoe/stable-diffusion-webui-ux/assets/54422205/b4d0808f-e75b-425c-b8d9-08d1bbc0ce8e">

### Console logs

```Shell
not needed
```

**Comment by anapnoe** [comment]
remove canvas zoom and reinstall the ui-ux it seems like this is causing the issue
