### ISSUE TITLE
[Bug]: additional networks grayed out

### ISSUE THREAD

**Issue by halr9000** [anapnoe/stable-diffusion-webui-ux#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

It's back :( 

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/9a3fe333-cb50-4503-a734-5b9e5b86cece)

### Steps to reproduce the problem

1. clean start
2. go to add'l networks 
3. it's all grayed out

### What should have happened?

normal colors

### Commit where the problem happens

b4adfff15a659d109bd9a3bf49acee4ff0103bf2

### What platforms do you use to access the UI ?

Windows, iOS, Android

### What browsers do you use to access the UI ?

Google Chrome, Apple Safari

### Command Line Arguments

```Shell
Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --api --xformers --update-all-extensions --ckpt-dir=D:\hal\stable-diffusion\models\Stable-diffusion --lora-dir=D:\hal\stable-diffusion\models\Lora --embeddings-dir=D:\hal\stable-diffusion\models\Embeddings --hypernetwork-dir=D:\hal\stable-diffusion\models\Hypernetworks
```

### List of extensions

a1111-sd-webui-locon
a1111-sd-webui-lycoris
a1111-sd-webui-tagcomplete
depthmap2mask
multidiffusion-upscaler-for-automatic1111
OneButtonPrompt
sd-canvas-editor
sd-dynamic-prompts
sd-extension-system-info
sd-webui-3d-open-pose-editor
sd-webui-ar
sd-webui-controlnet
sd-webui-enable-checker
sd-webui-infinite-image-browsing
sd-webui-inpaint-anything
sd-webui-regional-prompter
sd-webui-segment-anything
Stable-Diffusion-Webui-Civitai-Helper
stable-diffusion-webui-composable-lora
stable-diffusion-webui-promptgen
stable-diffusion-webui-randomize
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
PS D:\hal\stable-diffusion\ux> .\webui-user.bat
venv "D:\hal\stable-diffusion\ux\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Version: <none>
Commit hash: b4adfff15a659d109bd9a3bf49acee4ff0103bf2
Installing requirements
Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...

Installing sd-dynamic-prompts requirements.txt






Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\a1111-sd-webui-locon':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\a1111-sd-webui-lycoris':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\a1111-sd-webui-tagcomplete':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\depthmap2mask':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\OneButtonPrompt':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-canvas-editor':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-dynamic-prompts':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-extension-system-info':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-3d-open-pose-editor':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-ar':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-controlnet':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-enable-checker':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-infinite-image-browsing':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-inpaint-anything':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-regional-prompter':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\sd-webui-segment-anything':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\Stable-Diffusion-Webui-Civitai-Helper':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\stable-diffusion-webui-composable-lora':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\stable-diffusion-webui-promptgen':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\stable-diffusion-webui-randomize':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\stable-diffusion-webui-two-shot':
Already up to date.

Pulled changes for repository in 'D:\hal\stable-diffusion\ux\extensions\ultimate-upscale-for-automatic1111':
Already up to date.

Launching Web UI with arguments: --listen --enable-insecure-extension-access --no-half --api --xformers --update-all-extensions --ckpt-dir=D:\hal\stable-diffusion\models\Stable-diffusion --lora-dir=D:\hal\stable-diffusion\models\Lora --embeddings-dir=D:\hal\stable-diffusion\models\Embeddings --hypernetwork-dir=D:\hal\stable-diffusion\models\Hypernetworks
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\hal\stable-diffusion\ux\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading weights [9aba26abdf] from D:\hal\stable-diffusion\models\Stable-diffusion\sd15\deliberate_v2.safetensors
Creating model from config: D:\hal\stable-diffusion\ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(33): 16-token-negative-deliberate-neg, AS-Adult-neg, AS-Young, AS-Young-neg, AS-Younger, AS-Youngest, Asian-Less, Asian-Less-Neg, Bsft, dangerdonkey, easynegative, fractal-flame, gothbuilding, hrgiger-drmacabre, Isometric_Dreams, kc16-4000-sd1-5, kkw-micro, ng_deepnegative_v1_75t, photozoov15, Planit, qualityzoov15, renderzoov15, structurezoov15, Style-Glass, Style-Info, style-paintmagic, Style-Psycho, Style-Renaissance, style-rustmagic, Style-Winter, vintagemap_f, was-dieselpunk, was-mecha
Textual inversion embeddings skipped(10): dangerhorse, Neg_Facelift768, nfixer, nrealfixer, photozoov21, DrD_PNTE768, Painted_Landscape, ParchArt, Davespacefour, Knollingcase
Model loaded in 7.9s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 4.6s, move model to device: 1.1s, load textual inversion embeddings: 1.7s).
ControlNet v1.1.183
ControlNet v1.1.183
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 27.6s (import torch: 2.4s, import gradio: 1.2s, import ldm: 0.7s, other imports: 1.1s, load scripts: 11.7s, create ui: 3.6s, gradio launch: 6.7s).
```

### Additional information

see also https://github.com/anapnoe/stable-diffusion-webui-ux/issues/141

**Comment by anapnoe** [comment]
this issue is really annoying can you remove the paths from the cmd args and use a simlink to test?

**Comment by halr9000** [comment]
I have a ton of LORAs. I just had a thought to see if I can reproduce it in auto upstream. (Which might not even make sense if your code for this area diverged too much?)

**Comment by halr9000** [comment]
> this issue is really annoying can you remove the paths from the cmd args and use a simlink to test? 
> the green dot on the upper left indicates that the loading is stuck
> and of course I cant reproduce this issue on my machine 

Looks like I have 348. Possible I have a problem lol 

`PS D:\hal\stable-diffusion\models> ls lora -rec -inc *sors | measure
Count             : 348`

I'm thinking the loading is stuck because it's timing out. Do you know where the time out is top of your head? I can do a quick monkey patch to see if that fixes and let you know.

**Comment by halr9000** [comment]
> this issue is really annoying can you remove the paths from the cmd args and use a simlink to test? the green dot on the upper left indicates that the loading is stuck and of course I cant reproduce this issue on my machine

Didn't help

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/8e16a88e-9144-4876-93a2-694dbfabaf3b)

**Comment by halr9000** [comment]
Ok stripped out models. On to extensions...

![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/4bd02750-bf6e-4d0d-8208-72473f4dd090)

**Comment by halr9000** [comment]
Works w/o extensions. Putting my networks back in.

**Comment by halr9000** [comment]
Re-enabled these extensions and it is still working. Putting in the most recently updated ones, one-at-a-time. (And praying it's not a sporadic issue and I'm wasting time.)

a1111-sd-webui-locon
a1111-sd-webui-lycoris
a1111-sd-webui-tagcomplete
depthmap2mask
sd-canvas-editor
sd-dynamic-prompts
sd-extension-system-info
sd-webui-3d-open-pose-editor
sd-webui-ar
sd-webui-controlnet
sd-webui-enable-checker
sd-webui-inpaint-anything
sd-webui-segment-anything
Stable-Diffusion-Webui-Civitai-Helper
stable-diffusion-webui-composable-lora
stable-diffusion-webui-randomize
ultimate-upscale-for-automatic1111

**Comment by halr9000** [comment]
This mean anything? 

```
main.js?1684610298.6441388:5 Uncaught ReferenceError: extras_gallery is not defined
    at window.a1111minipaint.onload (main.js?1684610298.6441388:5:65)
    at HTMLIFrameElement.onload ((index):1:16)
```

**Comment by halr9000** [comment]
Has to be some sort of race condition. After removing all extensions, then putting some back in, I was able to get it to break. HOWEVER, it's breaking with different extensions! Almost as if (just a guess), the time taken to load the set of extensions is exceeding some limit, and that causes the extras_gallery to not get loaded (unless that's a red herring), and that leads to the networks never finishing loading, and the grayed out UI.

**Comment by halr9000** [comment]
Closing this for now as it seems to have gone away for the moment.
