### ISSUE TITLE
[Feature Request]: Incorporate yusing's text2img Optimizations

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

A user called yusing recently announced that they managed to make some heavy speed and VRAM improvements to text2img for the Auto1111 UI. The changes are also apparently being incorporated into the vlad fork as well. Since this is also a fork of Auto1111, it might be possible to apply these optimizations here as well.

Here's the reddit post where yusing speaks about their optimizations: https://www.reddit.com/r/StableDiffusion/comments/13o867l/i_made_some_changes_in_automatic1111_sd_webui/

Here's the link to the fork that utilizes their optimizations: https://github.com/yusing/stable-diffusion-webui

![Screenshot 2023-05-22 015200](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/0b7fe0f6-8614-429a-8a07-1ded459e48b5)

### Proposed workflow

1. Go to text2img
2. Press Generate
3. Images generate faster

**Comment by WildBanjos** [comment]
So. I remember when that was posted I looked through the repo trying to figure out the diff in the changes. Most of them seem fairly involved. The only change that was straightforward was replacing pillow with pillow-simd, which can be as simple as changing the requirements.txt or updating the venv if it's an existing install.
