### ISSUE TITLE
[Bug]: Randomize Seed And Reuse Seed Button Stops Working After Manual Seed Input

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

If you enter a seed manually into the seed input box, and generate. The 2 buttons to enable randomize speed and re-use selected image seed stops working.

### Steps to reproduce the problem

1. Go to .... text to image, input manually seed numbers
2. Press ....generate
3. Afterwards Randomize Seed Button + Reuse Seed button stops working until you restart the UI.

### What should have happened?

Button should work.

### Commit where the problem happens

59fda87

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --autolaunch
```

### List of extensions

Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper | 920ca326 (Tue May 23 11:53:22 2023) | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | b0d24ca6 (Wed May 17 00:19:32 2023) | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git | 50f5f889 (Mon May 22 19:44:01 2023) | unknown
sd-extension-system-info | https://github.com/vladmandic/sd-extension-system-info.git | 79243697 (Thu May 18 11:01:58 2023) | unknown
sd-webui-3d-open-pose-editor | https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git | f2d5aac5 (Sat Apr 15 13:21:06 2023) | unknown
sd-webui-additional-networks | https://github.com/kohya-ss/sd-webui-additional-networks.git | e9f3d622 (Tue May 23 12:31:15 2023) | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | 54f7c64b (Wed May 24 03:07:30 2023) | unknown
sd-webui-cutoff | https://github.com/hnmr293/sd-webui-cutoff | 3a073e9c (Wed May 3 07:14:40 2023) | unknown
sd-webui-supermerger | https://github.com/hako-mikan/sd-webui-supermerger.git | 7398bd8d (Tue May 23 15:57:48 2023) | unknown
stable-diffusion-webui-dataset-tag-editor | https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git | 43b0478f (Tue May 2 13:29:24 2023) | unknown
stable-diffusion-webui-state | https://github.com/ilian6806/stable-diffusion-webui-state.git | 8560a9c9 (Mon May 8 13:24:04 2023) | unknown
LDSR | built-in |   |  
Lora | built-in |   |  
ScuNET | built-in |   |  
SwinIR | built-in |   |  
prompt-bracket-checker | built-in |   |  
sd_theme_editor

<br class="Apple-interchange-newline">
</body>
</html>Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper	[920ca326 (Tue May 23 11:53:22 2023)](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	unknown
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git	[b0d24ca6 (Wed May 17 00:19:32 2023)](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git/commit/b0d24ca645b6a5cb9752169691a1c6385c6fe6ae)	unknown
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	[50f5f889 (Mon May 22 19:44:01 2023)](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git/commit/50f5f88944427a1f7e1321917790dbd9a5ddbed8)	unknown
sd-extension-system-info	https://github.com/vladmandic/sd-extension-system-info.git	[79243697 (Thu May 18 11:01:58 2023)](https://github.com/vladmandic/sd-extension-system-info.git/commit/79243697a23602ff4f9e441aa35fcfdc33bf0872)	unknown
sd-webui-3d-open-pose-editor	https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git	[f2d5aac5 (Sat Apr 15 13:21:06 2023)](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git/commit/f2d5aac51d891bc5f266b1549f3cf4495fc52160)	unknown
sd-webui-additional-networks	https://github.com/kohya-ss/sd-webui-additional-networks.git	[e9f3d622 (Tue May 23 12:31:15 2023)](https://github.com/kohya-ss/sd-webui-additional-networks.git/commit/e9f3d622b5a98650008a685ea23b27eb810da35a)	unknown
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	[54f7c64b (Wed May 24 03:07:30 2023)](https://github.com/Mikubill/sd-webui-controlnet.git/commit/54f7c64b4dc4a4206e76a152651d5f0b0fac248f)	unknown
sd-webui-cutoff	https://github.com/hnmr293/sd-webui-cutoff	[3a073e9c (Wed May 3 07:14:40 2023)](https://github.com/hnmr293/sd-webui-cutoff/commit/3a073e9c4525c21b72ae4645125768457c9c98e1)	unknown
sd-webui-supermerger	https://github.com/hako-mikan/sd-webui-supermerger.git	[7398bd8d (Tue May 23 15:57:48 2023)](https://github.com/hako-mikan/sd-webui-supermerger.git/commit/7398bd8d5b16330c45e0ad24507bf2d4abbd18b1)	unknown
stable-diffusion-webui-dataset-tag-editor	https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git	[43b0478f (Tue May 2 13:29:24 2023)](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git/commit/43b0478f1ec69e3112230e12ca47a69bc63227fb)	unknown
stable-diffusion-webui-state	https://github.com/ilian6806/stable-diffusion-webui-state.git	[8560a9c9 (Mon May 8 13:24:04 2023)](https://github.com/ilian6806/stable-diffusion-webui-state.git/commit/8560a9c9ebd3eefc63008f173db69b3168df3a2e)	unknown
LDSR	[built-in](http://127.0.0.1:7860/)		
Lora	[built-in](http://127.0.0.1:7860/)		
ScuNET	[built-in](http://127.0.0.1:7860/)		
SwinIR	[built-in](http://127.0.0.1:7860/)		
prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)		
sd_theme_editor

### Console logs

```Shell
nothing unusual
```

**Comment by anapnoe** [comment]
did the last update fix this issue ?

**Comment by rushuna86** [comment]
nope, still there

**Comment by anapnoe** [comment]
fixed update to the latest
