### ISSUE TITLE
[Bug]: missing svg files in style.css

### ISSUE THREAD

**Issue by blueball81** [anapnoe/stable-diffusion-webui-ux#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

In certain tabs, I am receiving the following error message in the console, which suggests that some svg files are missing. 
I have looked up the files in this repository, and I cannot find those files either. 

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

No error in the console. 
those files should be included here, or not used in style.css

### Commit where the problem happens

e04c3dd

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### List of extensions

-

### Console logs

```Shell
RuntimeError: File at path E:\stable-diffusion-webui\html\svg\spotlight\theme.svg does not exist.

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\stable-diffusion-webui\\html\\svg\\spotlight\\arrow.svg'

RuntimeError: File at path E:\stable-diffusion-webui\html\svg\spotlight\preloader.svg does not exist.
```

**Comment by anapnoe** [comment]
I added the files thanks
