### ISSUE TITLE
[Bug]: Directory for temporary images; leave empty for default Option No longer working

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Setting custom temp folder for images no longer working

### Steps to reproduce the problem

1. Go to .... Setting Saving/Images/grid
2. Change Directory for temporary images; leave empty for default
3. Generate images, temp images still get saved in %username%/AppData/Temp

### What should have happened?

Should save in custom directory if set.

### Commit where the problem happens

9931e86

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --autolaunch
```

### List of extensions

built in.

### Console logs

```Shell
nothing out of the ordinary
```

**Comment by anapnoe** [comment]
this is a bug I can confirm I will look into it

**Comment by rushuna86** [comment]
latest commit seems to also have fixed this issue.
