### ISSUE TITLE
[Bug]: Upscaling in extras no longer keeps prompt information

### ISSUE THREAD

**Issue by silvri** [anapnoe/stable-diffusion-webui-ux#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

In previous versions, after upscaling in extras, you could put an image in PNG Info and it would display the prompt in "parameters". For images generated in this version the "parameters" section just displays info about upscaling.

![Screenshot 2023-06-09 130310](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8032190/e0229f55-5751-420d-96b3-1d029d100f93)

![Screenshot 2023-06-09 130852](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8032190/f01e7fce-1dda-473a-b83f-3462e9a4ac1a)

### Steps to reproduce the problem

1. Generate an image
2. Send to extras and upscale image
3. Download image by dragging image to Windows desktop or folder
4. Reupload image in PNG Info tab

### What should have happened?

The prompt should have been displayed under "parameters"

### Commit where the problem happens

9931e86

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--listen --xformers --no-half-vae --medvram
```

### List of extensions

![Screenshot 2023-06-09 130350](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/8032190/661ccaf9-a816-479f-a5cd-007a9aa1d22c)

### Console logs

```Shell
C:\stable-diffusion-webui-ux>webui.bat --listen --xformers --no-half-vae --medvram
venv "C:\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: <none>
Commit hash: 9931e861dfb128735c4a928a7beb5b5c0af30593
Installing requirements

Launching Web UI with arguments: --listen --xformers --no-half-vae --medvram
2023-06-09 13:07:00,869 - ControlNet - INFO - ControlNet v1.1.217
ControlNet preprocessor location: C:\stable-diffusion-webui-ux\extensions\sd-webui-controlnet\annotator\downloads
2023-06-09 13:07:01,220 - ControlNet - INFO - ControlNet v1.1.217
Loading weights [77b7dc4ef0] from C:\stable-diffusion-webui-ux\models\Stable-diffusion\meinamix_meinaV10.safetensors
Creating model from config: C:\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: xformers... done.
Textual inversion embeddings loaded(9): Asian-Less-Neg, bad-picture-chill-32v, BadDream, CyberRealistic_Negative, EasyNegative, EasyNegativeV2, FastNegativeEmbedding, negative_hand, UnrealisticDream
Model loaded in 7.5s (load weights from disk: 0.6s, create model: 0.5s, apply weights to model: 4.8s, apply half(): 1.5s).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.2s (import torch: 3.9s, import gradio: 3.0s, import ldm: 1.2s, other imports: 2.8s, setup codeformer: 0.1s, load scripts: 2.1s, create ui: 8.3s, gradio launch: 4.5s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.80it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:15<00:00,  1.26it/s]
Total prTile 1/1500%|██████████████████████████████████████████████████████████████████| 20/20 [00:15<00:00,  4.01it/s]
        Tile 2/15
        Tile 3/15
        Tile 4/15
        Tile 5/15
        Tile 6/15
        Tile 7/15
        Tile 8/15
        Tile 9/15
        Tile 10/15
        Tile 11/15
        Tile 12/15
        Tile 13/15
        Tile 14/15
        Tile 15/15
```

### Additional information

My earlier images may not have been generated using xformers.

**Comment by rushuna86** [comment]
this issue is fixed in the main automatic1111 just needs this fork to pull that release

**Comment by anapnoe** [comment]
updated
