### ISSUE TITLE
[Feature Request]: Aspect ratio lock

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Allow the user to easily scale image size while preserving aspect ratio.

### Proposed workflow

1. Press the open lock button near width and height. It will turn into a closed lock.
2. Change either width or height.
3. The opposite dimension will scale to preserve the aspect ratio.
4. I believe there's a limitation that means the dimensions must be multiples of 8, if this is true then the opposite dimension's slider will turn red until it is a valid value.

**Comment by anapnoe** [comment]
it seems so, this is a feature of great value I agree I will add it in my todo list thanks

**Comment by bryanray** [comment]
it is call aspect ratio helper, latest ver is broken in this repo

**Comment by bryanray** [comment]
it is call aspect ratio helper, latest ver is broken in this repo

**Comment by anapnoe** [comment]
You send same message 3 times probably unintentionally
The current repo will not update to an unstable release from master the problem is that there is no versioning system with the extensions so if you try to install the latest update from the extension panel inside the ui,  it will download the latest release which is incompatible with the previous stable releases in order to make it work you need to go to the extension repository and download the previous commit of the extension, download and extract it in the extensions folder if the one you download doesn't work either then go and repeat the process until you find the one that works

**Comment by bryanray** [comment]
> You send same message 3 times probably unintentionally The current repo will not update to an unstable release from master the problem is that there is no versioning system with the extensions so if you try to install the latest update from the extension panel inside the ui, it will download the latest release which is incompatible with the previous stable releases in order to make it work you need to go to the extension repository and download the previous commit of the extension, download and extract it in the extensions folder if the one you download doesn't work either then go and repeat the process until you find the one that works

yup i am on proxy, it must be duplicated, it happened sometimes

**Comment by BinaryQuantumSoul** [comment]
This is a good feature proposition. Another good possibility could be to have an aspect ratio picker with common 1:1, 16:9, etc. in the place of the lock button. Or both of them, next to the switch width/height buttons

**Comment by BinaryQuantumSoul** [comment]
Actually, you could cooperate to implement this extension by default. It does exactly what is asked here: lock and aspect ratio selector. https://github.com/thomasasfk/sd-webui-aspect-ratio-helper

**Comment by FutonGama** [comment]
> 

Well the extension is working in general but only one thing is not working correctly, the Locker icon is not resizing the slider for some reason, i'm trying to discover here and the only thing i know is related to the sd_theme_editor, removing that works but i don't want to remove it so i'm trying to discover a way to fix.

**Comment by GeneralAwareness** [comment]
That did not work for me with the last update.

![image](https://user-images.githubusercontent.com/124339252/236846888-7426ea65-54b0-4469-ac1f-1fa040523137.png)
