### ISSUE TITLE
[Bug]:  Canvas Move + Inpaint Zoom keyboard shortcut effecting the whole inpaint Window

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When holding F during inpainting to move canvas, it actually moves the whole inpainting window. Shift + Mouse scroll also effecting the whole inpaint window and not just the canvas.

### Steps to reproduce the problem

1. Go to .... Inpaint
2. Press  and hold F and click move picture

### What should have happened?

I'm assuming this feature should only move the inpaint canvas not the whole inpainting window?

### Version or Commit where the problem happens

355c0ef

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### Cross attention optimization

sdp

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --autolaunch
```

### List of extensions

built-in

### Console logs

```Shell
nothing unusual
```

**Comment by anapnoe** [comment]
yes this is the official upstream implementation on canvas zoom so either disable the inbuild extension or don't use the shortcuts
until I add them for ui-ux I didn't remove the extension cause the paint brush size can be useful
