### ISSUE TITLE
[Bug]: After installing this plugin from sd-webui-agent-scheduler, I am unable to select the UX theme and the queue button

### ISSUE THREAD

**Issue by evakenshin** [anapnoe/stable-diffusion-webui-ux#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

"After installing this plugin from https://github.com/ArtVentureX/sd-webui-agent-scheduler, I am unable to select the UX theme and the queue button associated with this plugin does not appear on the interface."

### Steps to reproduce the problem

...

### What should have happened?

...

### Version or Commit where the problem happens

1.4.0

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Nvidia GPUs (RTX 20 above)

### Cross attention optimization

xformers

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
..
```

### List of extensions

sd-webui-agent-scheduler

### Console logs

```Shell
..
```

### Additional information

..

**Comment by AdrianAguilarT** [comment]
I have the same issue, even the plugin section doesn't work.
For now I just add in a user.css to keep typing and sending to queue, then I look the results with Image Browser.
```
.token-counter {
    pointer-events: none;
}
```
