### ISSUE TITLE
[Bug]: Ctrl+Enter doesn't generate on img2img

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Ctrl+Enter does nothing on img2img

### Steps to reproduce the problem

1. Go to img2img.
2. Press Ctrl+Enter.
3. Nothing.

### What should have happened?

It starts generating.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/802fb8a16ba4bdbfba0dca55f9cdb265f4bd86f2

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui
embedding-inspector
sd-dynamic-prompts
sd-dynamic-thresholding
sd-webui-controlnet
sd-webui-model-converter
stable-diffusion-webui-Prompt_Generator
stable-diffusion-webui-anti-burn
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
.
```

**Comment by anapnoe** [comment]
It works for me as it should strange this one I will leave this open if someone else can confirm that this is true I will investigate further thanks
