### ISSUE TITLE
[Feature Request]: favicon on browser tab

### ISSUE THREAD

**Issue by MaddyAurora** [anapnoe/stable-diffusion-webui-ux#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

There is already a favicon.ico file in the html folder but it simply doesn't work.
As an interface design it would be nice for it to work and show on browser tab.
Thank you in advance.

**Comment by anapnoe** [comment]
well its been added thank you 
small details do make a difference
