### ISSUE TITLE
[Feature Request]: Update to Auto 1.6

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Will this branch be updated to Auto 1.6? It should bring a in lot of new features, assuming it's stable.

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by matbee-eth** [comment]
Thats the issue with forks- unless its actively maintained it dies.
