### ISSUE TITLE
[Feature Request]: Support for --medvram-sdxl

### ISSUE THREAD

**Issue by Dajova** [anapnoe/stable-diffusion-webui-ux#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Simple. Add support for `--medvram-sdxl`.

Atm, it just spews out that it doesnt exist. `launch.py: error: unrecognized arguments: --medvram-sdxl`

### Proposed workflow

1. Edit commandline
2. Add `--medvram-sdxl`
3. Launch

**Comment by Zhincore** [comment]
This will probably come along when author updates to the newest automatic1111.

**Comment by anapnoe** [comment]
This project has not been abandon I have a lot of work implementing a unique layout engine along with a visual builder for gradio apps with most of the UI/UX features as an extension but still this fork will continue to implement core changes to optimize upon AUTO's version in many ways possible cheers
![preview](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/95cab8c0-86e7-4ad0-bde3-cd9f97d11f17)

**Comment by Dajova** [comment]
Any idea on when you're planning to go forward with the new update? I'm getting so many issues from extensions that doesn't support this current version of the webui, it's really limiting what i can and cannot do (including sdxl models).

**Comment by devioa** [comment]
> This project is under active development I have a lot of work implementing a unique layout engine along with a visual builder for gradio apps with most of the UI/UX features as an extension this fork will continue to introduce core changes to optimize upon AUTO's version in many ways possible if you like my work please support it cheers
> 
> ![preview](https://user-images.githubusercontent.com/124302297/272251886-95cab8c0-86e7-4ad0-bde3-cd9f97d11f17.png) ![visual-builder](https://user-images.githubusercontent.com/124302297/272254641-f074e357-6e3a-4487-88fb-64b6139db6d9.png)

Wow, this looks great. When do you plan to update? Looking forward to it very much!

**Comment by anapnoe** [comment]
new version is finally here enjoy!

**Comment by Dajova** [comment]
Ok, i get the new update and it loads insanely fast now... So fast in fact that it errors out:
`01/11/2023 02:03:43 error | Ref 15 #tab_img2img #txt2img_dimensions_row `

**Comment by anapnoe** [comment]
does it stop there would you like to open an issue?

**Comment by Dajova** [comment]
It does, yeah. It just stops loading and never shows the UI. Should i open a new issue or post here?
