### ISSUE TITLE
[Feature Request]: Make text2img Metadata Panel Resizable

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

When viewing an image's info / metadata in the text2img window, the actual images shrink based on metadata size. If using a lot of extensions that add to metadata (e.g.: ControlNet, Adetailer, Cutoff), multiple Lora, or simply long prompts, the metadata panel can get pushed very high up, to the point of turning images miniscule. Saving multiple images only worsens the issue.
![Screenshot 2023-11-06 132155](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/1eb4fb36-1300-408b-a0d5-2540467102fe)

The ability to manually adjust the size of the metadata panel, images could be adjusted to reasonable sizes. Potentially, a scroll bar could be added to the metadata panel, dynamically changing as the panel is increased or decreased, making it possible to scroll through and read all metadata while keeping images at a practical size - which would be the best of both worlds.

### Proposed workflow

1. Go to text2img
2. Create an image with a lot of metadata
3. Press the View Info / Metadata button
4. Resize panel and scroll metadata to more easily view and compare image info

**Comment by anapnoe** [comment]
added max height for info panel

**Comment by Neverdusk** [comment]
> added max height for info panel

I updated to the latest commit, and I didn't see any change on my end. At one point, I downloaded a large batch of images, and the info panel's buttons completely disappeared into the UI.
![Screenshot 2023-11-07 201314](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/f154fe42-3da2-4c50-b0ca-facdd9d2f021)

**Comment by Neverdusk** [comment]
I've also noticed that batch count seems to repeat and stack embedding information, for some reason. Each successive image has the embeddings repeated one additional time, until the take up several lines of meta.
![Screenshot 2023-11-07 203709](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/fa766884-5d5b-4427-aa42-697ead95cfca)
The first image is normal, the second doubles the embeddings, the third triples the embeddings, and so-on.

**Comment by anapnoe** [comment]
no issue, can't reproduce, a scrollbar should appear when info height is greater than 33vh
![no_issue](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/2c6e8be3-5e83-49f8-8b0c-9c41a2a4b897)

**Comment by Neverdusk** [comment]
Reopened the UX and it works now. Not sure why it didn't update for me yesterday, but thanks for the fix!
