### ISSUE TITLE
[Bug]: Inpaint Anything installed but does not show up by name

### ISSUE THREAD

**Issue by drdancm** [anapnoe/stable-diffusion-webui-ux#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

It look like it is available under Segment Anything, but that is confusing.

### Steps to reproduce the problem

Install Inpaint Anything extension
Look for it by name under installed extensions

### What should have happened?

Should show up but it does not

### Sysinfo

HP Z840
Win10 64bit
RX-3090
128Gb RAM
Xeon CPU

### What browsers do you use to access the UI ?

Mozilla Firefox

### Console logs

```Shell
Not necessary
```

**Comment by anapnoe** [comment]
you need to restart the ui-ux better use a chromium based browser selector :has is not enabled by default in firefox
![Uploading inpaint_anything.png…]()
