### ISSUE TITLE
[Bug]: Tooltips for icons are missing

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://user-images.githubusercontent.com/116045189/225795778-6a18f5ae-a523-49f0-aa1d-2badb63a80d9.png)
![image](https://user-images.githubusercontent.com/116045189/225795791-81398d80-53c6-4945-ac63-fa1c516da7a2.png)

The above buttons don't have tooltips.

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

d812736d6e32879a164b9a18da325dbe9cce3824

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Ugh.
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui	
embedding-inspector	
sd-dynamic-prompts	
sd-dynamic-thresholding	
sd-webui-controlnet	
sd-webui-model-converter	
stable-diffusion-webui-Prompt_Generator	
stable-diffusion-webui-anti-burn	
stable-diffusion-webui-artists-to-study	
stable-diffusion-webui-images-browser	
stable-diffusion-webui-inspiration	
stable-diffusion-webui-two-shot	
ultimate-upscale-for-automatic1111

### Console logs

```Shell
Ugh.
```

**Comment by anapnoe** [comment]
they display fine on my end if anyone else can confirm that there is some issue with the tooltips

**Comment by MakingMadness** [comment]
Thanks for the reply, I disabled all extensions and now they are appearing, so I'll try and figure out which one is causing the problem.

**Comment by MakingMadness** [comment]
I ran out of time trying to diagnose this, I'm not getting consistent results when removing and readding extensions but when I remove them all the bug seems to disappear. I've updated my bug report to include my extensions.

**Comment by anapnoe** [comment]
I close this issue as it is related to an extension that probably hijacks the tooltips
