### ISSUE TITLE
[Bug]: side panel show/hide button hot zone does not use the entire width

### ISSUE THREAD

**Issue by halr9000** [anapnoe/stable-diffusion-webui-ux#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm playing with various UX settings, and noticed that I had trouble show/hide the side panels. Turns out the cause is that unlike all of the other icons, the hot zone for show/hide doesn't fill the entire button. See screenshot, clicks in the highlighted portion do nothing, only clicking inside the red square works.

![Screenshot 2023-11-21 074350](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/18482/b77c7eb9-4ba3-4582-a6ca-58238409c3ba)

### Steps to reproduce the problem

1. Enable labels (settings/ux/show  labels for aside tabs)
2. Click around a bunch

P.S. "aside tabs"? I did not know what to call this whole area, but "aside tab" was not on my list. :D 

### What should have happened?

Clicking anywhere in the box should do the thing.

### Sysinfo

n/a

### What browsers do you use to access the UI ?

Google Chrome

### Console logs

```Shell
n/a
```

**Comment by anapnoe** [comment]
I am actually thinking to remove this arrow to save some vertical space and use the icons to toggle the state of aside view 
now you need it only to close the aside view the open state is working if you click the same or a different aside tab when state is closed

**Comment by halr9000** [comment]
wait till you see my keyboard nav issue lol

**Comment by halr9000** [comment]
but either way -- this one icon hot zone is inconsistent to all of the rest
