### ISSUE TITLE
[Bug]: Inpaint Image Appears Behind Some UI Elements

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I've noticed that, when inpainting, some UI elements remain over the image, and other images are hidden behind it - instead of them all sliding down to accommodate for it. I tried disabling some extensions and then disabling all extra extensions, and the issue remained, so I believe it's inherent to the UI itself. This remained regardless of whether the sidebar was open or not. The only way to see the UI AND the inpaint image is to downsize the image and slide it around.
![Screenshot 2023-12-06 162439](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/70fc8437-c2ad-4cb1-9f72-f73ce31d2a1b)
![Screenshot 2023-12-06 162451](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/b08848d8-cfb8-4cd7-ad3f-821cd6086793)
![Screenshot 2023-12-06 162511](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/9feec192-ea22-4425-bbc8-186103c0ee7c)

### Steps to reproduce the problem

1. Go to Img2Img
2. Press Inpaint Tab
3. Drag-in or select an image to inpaint
4. Image appears both in front of and covering UI

### What should have happened?

The UI panel should have slide down to accommodate the image, allowing all settings to be visible beneath the picture and preventing any overlapping.

### Sysinfo

[sysinfo-2023-12-06-21-31.txt](https://github.com/anapnoe/stable-diffusion-webui-ux/files/13591805/sysinfo-2023-12-06-21-31.txt)

### What browsers do you use to access the UI ?

Google Chrome

### Console logs

```Shell
venv "C:\Users\silve\Documents\AI Art\__SDUX\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Version: v1.6.0-321-gda22a58a
Commit hash: da22a58aaeb6fe71046221c5068da9303db8314c
Launching Web UI with arguments: --api --medvram-sdxl --xformers --no-half-vae --autolaunch --opt-split-attention
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 23.11.1, num models: 14
2023-12-06 16:36:07,447 - ControlNet - INFO - ControlNet v1.1.419
ControlNet preprocessor location: C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-controlnet\annotator\downloads
2023-12-06 16:36:07,551 - ControlNet - INFO - ControlNet v1.1.419
Loading weights [4574b00913] from C:\Users\silve\Documents\AI Art\__SDUX\models\Stable-diffusion\__Anime\_Custom\Roxanne02.safetensors
Civitai Helper: Set Proxy:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\Users\silve\Documents\AI Art\__SDUX\configs\v1-inference.yaml
Startup time: 11.9s (prepare environment: 2.5s, import torch: 2.6s, import gradio: 0.7s, setup paths: 0.6s, initialize shared: 0.2s, other imports: 0.5s, list SD models: 0.2s, load scripts: 2.2s, create ui: 1.2s, gradio launch: 0.7s, app_started_callback: 0.2s).
Loading VAE weights specified in settings: C:\Users\silve\Documents\AI Art\__SDUX\models\VAE\Blessed2.vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 6.8s (load weights from disk: 1.8s, create model: 0.6s, apply weights to model: 3.8s, load VAE: 0.3s, calculate empty prompt: 0.1s).
```

**Comment by bobcate** [comment]
I was having the same problem and just found a solution.
There is talk in other threads about the extension called "canvas-zoom-and-pan" causing issues.
Turns out that extension is the reason for this issue as well.
The solution is disabling it and restarting the UI.

**Comment by Neverdusk** [comment]
> I was having the same problem and just found a solution. There is talk in other threads about the extension called "canvas-zoom-and-pan" causing issues. Turns out that extension is the reason for this issue as well. The solution is disabling it and restarting the UI.

You're definitely right. Canvas Zoom and Pan is really useful though, especially for careful inpainting. But if this gets to be too much of a pain, I might just disable it until a fix is made.
