### ISSUE TITLE
[Bug]: Division by 0 error

### ISSUE THREAD

**Issue by bobcate** [anapnoe/stable-diffusion-webui-ux#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Setting the "extra_options_cols" variable to 0 results in a bunch of errors and the UI doesn't launch.

### Steps to reproduce the problem

1. Launch the UI
2. Open Settings > User Interface
3. Set the "Options in main UI - number of columns" variable to 0 (zero)
4. Apply settings > Reload the UI
5. See the errors in the console

### What should have happened?

User should not be allowed to set that variable to 0, or less than 1 for good measure.

### What browsers do you use to access the UI ?

Opera GX

### Additional information

I was able to launch the UI after this happened by opening the "config.json" file and setting the value of "extra_options_cols" to 1.

**Comment by anapnoe** [comment]
The slider min value is set to 1
