### ISSUE TITLE
[Bug]: Issues related to mouse hovering. And Feature request.

### ISSUE THREAD

**Issue by falsonerd** [anapnoe/stable-diffusion-webui-ux#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

There are a few issues with mouse hovering in general...

- After you click on a input field to type your desired value ie: steps, if you hove your mouse outside that field it will deselect. 
![image](https://user-images.githubusercontent.com/50148645/228066637-9467a105-fb0b-4114-b204-1eb7573b03ed.png)

- After your prompt is generated and you scroll down in the generation info tab, hover your mouse somewhere else, you image will be cropped. (graphical bug only).
PS: It will go back to normal if you scroll up/down the left area...
![image](https://user-images.githubusercontent.com/50148645/228066586-b1c767ce-cbaa-4e94-a3ad-a3478902632d.png)

- On Inpainting tab, if you go full-screen with move tool selected and then press ESC to get back, Inpainting area will get stuck outside.
![image](https://user-images.githubusercontent.com/50148645/228067719-cf0cbf63-89a8-4176-96c7-8b79217dca28.png)

### Steps to reproduce the problem

Please check above.

### What should have happened?

- Be able to type even with mouse outside the "typing field"
- No cropped image
- Inpainting area working as usual

### Commit where the problem happens

cbfb4632585415dc914aff8c44869d792fd64c24

### What platforms do you use to access the UI ?

Other/Cloud

### Command Line Arguments

```Shell
--no-half-vae --xformers --enable-insecure-extension-access --no-hashing --lowram --gradio-queue --share
```

### List of extensions

![image](https://user-images.githubusercontent.com/50148645/228068981-02bf980c-ba4a-4897-9243-2bb49ecc7cea.png)

### Console logs

```Shell
No errors
```

### Additional information

• Feature request.
Add hover over text to these icons....
![image](https://user-images.githubusercontent.com/50148645/228067028-f51887e7-e802-416e-925f-e46b0be858fd.png)

**Comment by anapnoe** [comment]
Thank you for your valuable feedback all issues resolved and tooltips added to send to icons best regards
