### ISSUE TITLE
[Bug]: The UI will stuck in the intro console command, and wont launch, when having a bad internet

### ISSUE THREAD

**Issue by orangpelupa** [anapnoe/stable-diffusion-webui-ux#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

when having a bad internet with lots of time outs, the UI will stuck in the intro console command, and wont launch. easily reproducible by manually setting gateway to nonexistent one

### Steps to reproduce the problem

1. manually set your local ip address
2. set to a non-existent gateway (e.g. 192.168.0.0)
3. launch stable diffusion webui ux

### What should have happened?

it should show the UI once the intro console command finished doing its thing (usually in less than 1 second)

### Sysinfo

cannot be done, because the webui hasnt opened yet, it only showing the console command
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/16116746/c99490cc-877f-4df1-867d-99f6bcff3ddc)

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.1
Commit hash: 6029303af55dddbd9c60dae829c4e80a5dfa08fb
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --xformers --api --skip-python-version-check
12:08:48 - ReActor - STATUS - Running v0.6.0-a2
Loading weights [3a4b9e1210] from B:\tools\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion Web UI-UX\models\Stable-diffusion\asianrealisticSdlife_v40_realphoto_asian_aodai_suonxam_checkpoint_15.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: B:\tools\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion Web UI-UX\configs\v1-inference.yaml
Startup time: 23.0s (prepare environment: 7.4s, import torch: 4.8s, import gradio: 2.1s, setup paths: 2.3s, initialize shared: 0.3s, other imports: 1.6s, setup codeformer: 0.2s, list SD models: 0.3s, load scripts: 2.9s, create ui: 0.5s, gradio launch: 0.6s).
Applying attention optimization: xformers... done.
Model loaded in 3.0s (load weights from disk: 1.0s, create model: 0.3s, apply weights to model: 1.4s, calculate empty prompt: 0.1s).
```

**Comment by orangpelupa** [comment]
to be clear, 

- once the internet is working again, i can relaunch it and it works fine.
- after the webui has been launching properly, it doesnt matter if the internet is borked

**Comment by anapnoe** [comment]
cool that you figure this out 
but I don't think I will include this in the core
