### ISSUE TITLE
[Feature Request]: Scrolling / Scrollbar for Prompt Textboxes

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Add a scrollbar and the ability to scroll up and down for positive and negative prompts in text2img and img2img. 

Currently, if a prompt is longer than the input textbox, the only way to move up or down is by pressing up or down the keyboard. Otherwise, the top or bottom of the prompt is visibly cut off. A scrollbar and the ability to scroll prompt textboxes, similar to the one present on the information panel for generated images, would make scrolling prompts easier and more accessibly. It would also make prompting more compatible with touch and other non-keyboard inputs.

### Proposed workflow

1. Go to text2img
2. Write a long prompt
3. Drag the scroll bar or use the mouse wheel to view parts of the prompt cut off by the textbox.

**Comment by anapnoe** [comment]
Thank you never had to write a text so long :) it has been fixed
