### ISSUE TITLE
[Bug]: Latest branch bugs out the stop button

### ISSUE THREAD

**Issue by Dajova** [anapnoe/stable-diffusion-webui-ux#220]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [x] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/fafb0b581bb2b6ba78b62dfba8c95eee6925ce76
This branch makes the stop button for generations unusable. No matter what model i use, it doesnt stop the generation, even tho the UI indicates that it's stopped. And the only way to stop it is to close the console window itself.

### Steps to reproduce the problem

* update to latest branch.
* start generating anything.
* stop the generation.
* keeps on generating.

### What should have happened?

Should just stop generating the current batch.

### What browsers do you use to access the UI ?

Firefox.

### Sysinfo

-

### Console logs

```Shell
-
```

**Comment by anapnoe** [comment]
please test also with chrome browser 
it should work on firefox if you Go to the Firefox about:config page, then search and toggle layout. css.has-selector. enabled

**Comment by Dajova** [comment]
Did. tested firefox, chrome and edge, neither was able to stop the generation once it started. All browsers indicated that the generation was stopped in the UI, but kept on generating regardless.

**Comment by Dajova** [comment]
Ok, it seems this wasn't a bug after all, it was just a new option that was undocumented and enabled by default. Disabling this and it's fine again.
![image](https://i.imgur.com/eJc9hYi.png)
