### ISSUE TITLE
[Bug]: UI Errors After 1.8 Update

### ISSUE THREAD

**Issue by Neverdusk** [anapnoe/stable-diffusion-webui-ux#222]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I recently updated to 1.8 and noticed a few issues. I disabled all extra extensions and these issues remain.

Specifically, the sidebar often doesn't display any Checkpoints, Embeddings, or Loras in their respective tabs, and it never shows paths. Whenever the UI first loads, only a "Loading..." text is visible. Clicking the Reset button usually fixes the model buttons / images not appearing, but the path region still remains empty, making it impossible to filter by path.
![1](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/a9dab800-55e5-4216-ba6f-8a0006d04666)
![Screenshot 2024-03-25 024019](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/acee033a-3142-4e58-969a-bf18687071a4)

### Steps to reproduce the problem

1. Open UI
2. Open righthand sidebar
3. Try to view any model tab
4. Open path region and try to view paths

### What should have happened?

The sidebar should display all models and paths in their respective tabs.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-03-25-06-41.json](https://github.com/anapnoe/stable-diffusion-webui-ux/files/14739804/sysinfo-2024-03-25-06-41.json)

### Console logs

```Shell
venv "C:\Users\silve\Documents\AI Art\__SDUX\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Version: v1.6.0-1350-gfafb0b58
Commit hash: fafb0b581bb2b6ba78b62dfba8c95eee6925ce76
Launching Web UI with arguments: --api --medvram-sdxl --xformers --no-half-vae --autolaunch --opt-split-attention
==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.20.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Civitai Helper: Get Custom Model Folder
[-] ADetailer initialized. version: 24.3.2, num models: 15
ControlNet preprocessor location: C:\Users\silve\Documents\AI Art\__SDUX\extensions\sd-webui-controlnet\annotator\downloads
2024-03-25 02:22:47,305 - ControlNet - INFO - ControlNet v1.1.441
2024-03-25 02:22:47,449 - ControlNet - INFO - ControlNet v1.1.441
[Vec. CC] Style Sheet Loaded...
Loading weights [4574b00913] from C:\Users\silve\Documents\AI Art\__SDUX\models\Stable-diffusion\__Anime\_Custom\Roxanne02.safetensors
Creating model from config: C:\Users\silve\Documents\AI Art\__SDUX\configs\v1-inference.yaml
2024-03-25 02:22:49,712 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Set Proxy:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 17.4s (prepare environment: 3.6s, import torch: 4.0s, import gradio: 1.0s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.7s, list SD models: 0.2s, load scripts: 3.6s, create ui: 1.7s, gradio launch: 0.3s, add APIs: 1.1s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: C:\Users\silve\Documents\AI Art\__SDUX\models\VAE\CleanVAE.vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 12.6s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 10.7s, apply dtype to VAE: 0.2s, load VAE: 0.5s, calculate empty prompt: 0.1s).
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Version: v1.6.0-1350-gfafb0b58
Commit hash: fafb0b581bb2b6ba78b62dfba8c95eee6925ce76
Launching Web UI with arguments: --api --medvram-sdxl --xformers --no-half-vae --autolaunch --opt-split-attention
==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.20.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
*** "Disable all extensions" option was set, will only load built-in extensions ***
Loading weights [4574b00913] from C:\Users\silve\Documents\AI Art\__SDUX\models\Stable-diffusion\__Anime\_Custom\Roxanne02.safetensors
Creating model from config: C:\Users\silve\Documents\AI Art\__SDUX\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.1s (prepare environment: 2.3s, import torch: 4.1s, import gradio: 1.0s, setup paths: 0.8s, initialize shared: 0.1s, other imports: 0.7s, list SD models: 0.2s, load scripts: 1.3s, create ui: 1.1s, gradio launch: 0.1s, add APIs: 0.2s).
Loading VAE weights specified in settings: C:\Users\silve\Documents\AI Art\__SDUX\models\VAE\CleanVAE.vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 4.1s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 2.8s, load VAE: 0.4s, calculate empty prompt: 0.1s).
```

**Comment by anapnoe** [comment]
Hello, it appears that your system information has not been updated correctly. According to the information you provided, the version is listed as "Version: v1.6.0-1350-gfafb0b58" instead of "Version: v1.8.0-343-gfafb0b58." Please run the command line flag --reinstall-torch --reinstall-xformers. Thank you.

**Comment by Neverdusk** [comment]
I ran those commands it shortly after filing this report (since I also noticed the alert) and the issue remained. Both torch and xformers are updated. The version is still listed as 1.6, but I've already updated my install to the latest commit.

![Screenshot 2024-03-26 230100](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/5bbd0b19-f733-4c0b-9e6e-1fea9c53fcb3)
![Screenshot 2024-03-26 230759](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/1d4bbd3c-129c-46e2-a20d-95ecd30dfae2)
![Screenshot 2024-03-26 230812](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/6d7c5fb1-b76a-4846-8904-64faf9d7b2b6)

**Comment by Neverdusk** [comment]
To add, I just completed a completely new install and I can confirm that the "Loading..." error is still active.

**Comment by anapnoe** [comment]
Please consider doing a fresh install by downloading the zip file or running the git clone command. Then, run the webui-user.bat file and you should see the desired outcome. Thank you.
![1 8 0-RC](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/82d0a0a4-ff80-43ef-bb19-336efe159be0)

**Comment by Neverdusk** [comment]
I made a fresh, fully-updated install and I'm still having the same UI errors. Models don't appear until I refresh the UI, and paths are empty no matter what I do, making it impossible to browse via folder within the UI.



![1](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/180c19c8-8364-49f4-af27-eeacf73cf27c)
![2](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/2a013993-4fa9-4a51-9938-8e554609c8a9)
![3](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/c9c24f61-983b-47c4-8275-aa9de64d2e84)
![5](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/79533944/9576dd3e-bc70-47a9-b131-487a18f4e759)

**Comment by anapnoe** [comment]
it appears that there may be a caching issue with your browser. To resolve this, could you please try the following steps on Chrome: right-click, select "Inspect Element," then right-click on the refresh button and choose "Empty Cache and Hard Reload"?
![1 8 0-RC](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/124302297/22eabe0d-bb11-419d-89f1-72fd31eefa9c)

**Comment by Neverdusk** [comment]
Thank you! I just tried this, and I think it works now. I appreciate the assistance a lot.
