### ISSUE TITLE
fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by tampadesignr** [anapnoe/stable-diffusion-webui-ux#231]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

fresh install line is right after the venv 

### Steps to reproduce the problem

did a clone and message is in setup

### What should have happened?

tried to research it and it seems to be a git something issue
if i copy the git folder from an auto1111 install into the dir the error goes away
it appears the --tag is missing

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

none

### Console logs

```Shell
none
```

**Comment by anapnoe** [comment]
I just completed a fresh installation, and I haven't encountered this message. If anyone else is experiencing the same issue, please let me know so I can investigate further.

**Comment by tampadesignr** [comment]
i git bash to destination
run git clone
haven't had this error with auto1111, forge, sd.next (trying to find my home)
i like your interface and speed but afraid what this error could me down the road and what its affecting now
all my research keep coming back to something related to the branch / head
mind you i am an artist first, but 25 years later i somewhat get through the coding

https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything
https://stackoverflow.com/questions/10268641/jenkins-git-plugin-git-describe-cannot-describe-anything
https://github.com/mail-in-a-box/mailinabox/issues/2274

**Comment by anapnoe** [comment]
Thank you, the issue is resolved. I'm not sure why it occurred, but running a git push --tags from my local machine fixed it.
