### ISSUE TITLE
[Bug]: lora site panel brokenview

### ISSUE THREAD

**Issue by NodokaMurmevent** [anapnoe/stable-diffusion-webui-ux#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

when i open the lora tabs and use the folders buttons. it’s broken. i see many «no picture image» at the top and bottom.

also if i have :  
myLora.safetensor
myLora.png
myLora.text

the text seam to break the grid

### Steps to reproduce the problem

1. Go to side view
2. Press on lora
3. press on folder

### What should have happened?

no broken display

### Commit where the problem happens

958667f

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --medvram --no-half-vae --no-half --precision full --autolaunch
```

### List of extensions

a1111-sd-webui-tagcomplete 
sd-webui-ar
stable-diffusion-webui-images-browser 
ultimate-upscale-for-automatic1111

### Console logs

```Shell
venv "E:\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 958667f3f391a053096717e678e95c4b889d6391
Installing requirements for Web UI

Launching Web UI with arguments: --xformers --medvram --no-half-vae --no-half --precision full --autolaunch
Loading weights [HIDDEN] from [HIDDEN]
Creating model from config: E:\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(9): [HIDDEN]
Model loaded in 2.1s (load weights from disk: 0.1s, create model: 0.4s, apply weights to model: 1.5s, load textual inversion embeddings: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.8s (import gradio: 2.8s, import ldm: 1.1s, other imports: 2.1s, list extensions: 0.6s, load scripts: 2.4s, load SD checkpoint: 2.3s, create ui: 1.1s, gradio launch: 0.3s).
```

**Comment by anapnoe** [comment]
fixed also I hide the annoying description text until I make a popup for it
