### ISSUE TITLE
[Bug]: The Image is stretched when uploaded to ControlNet Extension

### ISSUE THREAD

**Issue by Linaqruf** [anapnoe/stable-diffusion-webui-ux#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Like the title, the image is stretched when I upload it to ControlNet Extension.

What OS: I use Colab Notebook, https://colab.research.google.com/github/Linaqruf/sd-notebook-collection/blob/main/cagliostro-colab-ui.ipynb
What Browser: Google Chrome

![image](https://user-images.githubusercontent.com/50163983/229086312-a1a518da-3829-48bb-a8db-42ae513a535a.png)

I don't know exactly, but probably because `width` is used in `canvas {` in style.css instead of `max-width`. However, if `max-width` is used, it will also stretch `inpaint` images. Setting `width` to `auto` will probably solve the problem.

### Steps to reproduce the problem

1. Install https://github.com/Mikubill/sd-webui-controlnet
2. Go to ControlNet Accordion
3. Upload an Image

### What should have happened?

The image isn't stretched.

### Commit where the problem happens

608c684b0f5794b13b6cadc0ee76f584edff24ec

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--enable-insecure-extension-access --disable-safe-unpickle --multiple --share --no-half-vae --lowram --no-hashing --disable-console-progressbars --gradio-queue --opt-sub-quad-attention --opt-channelslast --theme dark --xformers
```

### List of extensions

    "https://github.com/KohakuBlueleaf/a1111-sd-webui-locon",
    "https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git",
    "https://github.com/etherealxx/batchlinks-webui",
    "https://github.com/mcmonkeyprojects/sd-dynamic-thresholding",
    "https://github.com/kohya-ss/sd-webui-additional-networks.git",
    "https://github.com/thomasasfk/sd-webui-aspect-ratio-helper.git",
    "https://github.com/Mikubill/sd-webui-controlnet",
    "https://github.com/camenduru/sd-webui-tunnels",
    "https://github.com/bbc-mc/sdweb-merge-block-weighted-gui.git",
    "https://github.com/bbc-mc/sdweb-xyplus",
    "https://github.com/catppuccin/stable-diffusion-webui",
    "https://github.com/opparco/stable-diffusion-webui-composable-lora.git",
    "https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git",
    "https://github.com/arenatemp/stable-diffusion-webui-model-toolkit",
    "https://github.com/opparco/stable-diffusion-webui-two-shot",
    "https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git"

### Console logs

```Shell
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 608c684b0f5794b13b6cadc0ee76f584edff24ec
Installing requirements for Web UI




Launching Web UI with arguments: --enable-insecure-extension-access --disable-safe-unpickle --multiple --share --no-half-vae --lowram --no-hashing --disable-console-progressbars --gradio-queue --opt-sub-quad-attention --opt-channelslast --theme dark --xformers
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
all detected, remote.moe trying to connect...
Warning: Permanently added the RSA host key for IP address '54.161.197.247' to the list of known hosts.
all detected, cloudflared trying to connect...
Loading weights [None] from /content/stable-diffusion-webui/models/Stable-diffusion/anylora.safetensors
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/stable-diffusion-webui/models/VAE/anime.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 20.6s (load weights from disk: 16.3s, create model: 2.3s, load VAE: 1.8s).
Public WebUI Colab URL (may contain ads): http://6ksbufxyvfimets6lwfyu2ubtkgrujcpd27n2yvovpkyeoosykua.remote.moe 
Public WebUI Colab URL: https://8c33f8b2-b43f-48c2.gradio.live 
Public WebUI Colab URL: https://c17c5ad690ec37.lhr.life
Please do not use this link we are getting ERROR: Exception in ASGI application:  https://db8b5258-6cc6-4b56.gradio.live
Public WebUI Colab URL: https://guyana-wrapped-holland-chess.trycloudflare.com
Startup time: 53.9s (import gradio: 3.9s, import ldm: 6.1s, other imports: 3.8s, list extensions: 1.2s, setup codeformer: 0.1s, load scripts: 14.0s, load SD checkpoint: 20.6s, create ui: 2.3s, gradio launch: 1.6s).
Interrupted with signal 2 in <frame at 0x77153610, file '/content/stable-diffusion-webui/webui.py', line 206, code wait_on_server>
```

**Comment by anapnoe** [comment]
for now you can change the
the css property to flex-grow: 0; 

```
div[data-testid="image"] > div {
    position: relative;
    max-height: 50vh;
    background-color: var(--main-bg-color);
    object-fit: contain;
    width: fit-content!important;
    height: fit-content !important;
    margin: auto;
    flex-grow: 0; 
}
```
this is a temporary fix until I extend the editing tools zoom-in pan etc. to be applied also to extensions image edit component

**Comment by Linaqruf** [comment]
Thank you!
