### ISSUE TITLE
[Bug]: Posex extension is broken.

### ISSUE THREAD

**Issue by falsonerd** [anapnoe/stable-diffusion-webui-ux#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Unable to properly use PoseX extension.
After you open the extension tab it seems it will open up properly.
![image](https://user-images.githubusercontent.com/50148645/229099987-7edda44f-f830-4b3b-9c32-0fc11d777b05.png)
![image](https://user-images.githubusercontent.com/50148645/229099353-7de86b2b-783b-4d05-9c7f-016dd186869b.png)
But shortly after it breaks.
![image](https://user-images.githubusercontent.com/50148645/229099476-1325b72a-05e4-420a-9db0-75eaab5ae26b.png)

Tested both in Opera GX and Chrome

### Steps to reproduce the problem

1.  Start WebUI
3. Go to PoseX tab. (check send to controlnet so it loads)
4. Wait...

### What should have happened?

1. Start WebUI
3. Go to PoseX tab. (check send to controlnet so it loads)
4. Extension works properly.

### Commit where the problem happens

608c684b0f5794b13b6cadc0ee76f584edff24ec

### What platforms do you use to access the UI ?

Other/Cloud

### What browsers do you use to access the UI ?
Opera Gx

### Command Line Arguments

```Shell
--no-half-vae --xformers --enable-insecure-extension-access --no-hashing --lowram --gradio-queue --autolaunch --allow-code --administrator
```

### List of extensions

<html>
<body>

Extension | URL | Version | Update
-- | -- | -- | --
StylePile | https://github.com/some9000/StylePile | abc71631 (Thu Dec 8 06:48:39 2022) | unknown
a1111-sd-webui-locon | https://github.com/KohakuBlueleaf/a1111-sd-webui-locon | 8e0ebd76 (Thu Mar 30 15:20:06 2023) | unknown
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete | 811d4622 (Tue Mar 28 18:49:09 2023) | unknown
batchlinks-webui | https://github.com/etherealxx/batchlinks-webui | fceda4d6 (Thu Mar 30 11:13:00 2023) | unknown
ddetailer | https://github.com/dustysys/ddetailer | 22a17414 (Mon Nov 28 09:33:31 2022) | unknown
posex | https://github.com/hnmr293/posex | 233daf8e (Tue Mar 7 12:21:57 2023) | unknown
sd-dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts | b020cb48 (Thu Mar 30 16:54:54 2023) | unknown
sd-webui-additional-networks | https://github.com/kohya-ss/sd-webui-additional-networks | 1fac0c35 (Wed Mar 29 23:50:38 2023) | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet | 241c05f8 (Thu Mar 23 15:18:35 2023) | unknown
sd-webui-depth-lib | https://github.com/jexom/sd-webui-depth-lib | 28a22387 (Mon Mar 6 21:02:28 2023) | unknown
sd-webui-lora-block-weight | https://github.com/hako-mikan/sd-webui-lora-block-weight | a6eaf753 (Fri Mar 31 03:31:40 2023) | unknown
sd-webui-model-converter | https://github.com/Akegarasu/sd-webui-model-converter | d19e2816 (Sun Mar 26 06:36:49 2023) | unknown
sd-webui-model-toolkit | https://github.com/arenatemp/stable-diffusion-webui-model-toolkit | 8d8f073f (Fri Feb 17 20:39:41 2023) | unknown
sd-webui-tunnels | https://github.com/camenduru/sd-webui-tunnels | b160e28d (Thu Mar 30 16:23:23 2023) | unknown
sd-webui-vae-blessup | https://github.com/sALTaccount/VAE-BlessUp | 14a86d11 (Sat Mar 11 00:00:01 2023) | unknown
stable-diffusion-webui-composable-lora | https://github.com/opparco/stable-diffusion-webui-composable-lora | d4963e48 (Mon Feb 27 17:40:08 2023) | unknown
stable-diffusion-webui-huggingface | https://github.com/camenduru/stable-diffusion-webui-huggingface | 6e824a1a (Tue Feb 28 20:53:14 2023) | unknown
stable-diffusion-webui-two-shot | https://github.com/ashen-sensored/stable-diffusion-webui-two-shot | c9861617 (Thu Mar 30 07:45:58 2023) | unknown

</body>
</html>

### Console logs

```Shell
/content/stable-diffusion-webui
env: LD_PRELOAD=libtcmalloc.so
env: SAFETENSORS_FAST_GPU=1
Using Gradio default tunnel...

Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 608c684b0f5794b13b6cadc0ee76f584edff24ec
Installing requirements for Web UI

Launching Web UI with arguments: --no-half-vae --xformers --enable-insecure-extension-access --no-hashing --lowram --gradio-queue --autolaunch --allow-code --administrator
2023-03-31 10:57:39.194012: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-31 10:57:42.014836: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
/usr/local/lib/python3.9/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Checkpoint 4Moon-Cuties.safetensors not found; loading fallback pdhass-half.safetensors
Loading weights [None] from /content/stable-diffusion-webui/models/Stable-diffusion/pdhass-half.safetensors
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/stable-diffusion-webui/models/VAE/PerfectColors.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(9): bad-Unspeakable_Horrors_Composition_4v, bad-EasyNegative, bad_prompt_version2, bad-artist, bad-Deepnegative_v1_75t, bad-hands-5, bad_rumorV1, bad-image-v2-39000, bad-handv4
Model loaded in 16.0s (load weights from disk: 8.7s, create model: 0.8s, apply weights to model: 2.7s, apply half(): 1.0s, load VAE: 1.9s, move model to device: 0.8s).
/usr/local/lib/python3.9/dist-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Blocks, please remove them: {'variant': 'compact'}
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Button, please remove them: {'full_width': True}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://XXXX.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Startup time: 48.5s (import gradio: 3.2s, import ldm: 7.8s, other imports: 4.1s, list extensions: 1.4s, setup codeformer: 0.1s, load scripts: 6.5s, load SD checkpoint: 16.0s, create ui: 4.5s, gradio launch: 4.8s).
```

### Additional information

Related in #19 
Openpose works fine.

Edit:
Using browser dev mode I can see this....
![image](https://user-images.githubusercontent.com/50148645/229105117-a320c421-68b9-447c-bc57-d9b780a1b455.png)

**Comment by anapnoe** [comment]
fixed the main display issue with Posex best regards

**Comment by falsonerd** [comment]
Thanks for your hard work.
