### ISSUE TITLE
[Feature Request]: A way of panning while zoomed in inpainting

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

At least on desktop I can't work out a way of panning around. I <3 your improved interface for inpainting!

### Proposed workflow

Hold right mouse to pan.
Mousewheel pans vertically.
Shift+mousewheel pans horizontally.

**Comment by anapnoe** [comment]
if you click on the toolbar the cross arrow item you can zoom with mouse wheel and pan with click and drag

**Comment by MakingMadness** [comment]
Can't we still have this as a QoL improvement? If I want to zoom in and out a lot, drawing as I go, this is very cumbersome.
