### ISSUE TITLE
[Feature Request]: Generation info visible by default on desktop

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

As a power user I constantly use the generation info. Would be nice to have.

### Proposed workflow

Look with eyes.

**Comment by anapnoe** [comment]
Generation info will stay open if you click on the accordion there is no reason to be open by default
