### ISSUE TITLE
[Bug]: Sometimes send to * doesn't change to the appropriate tab

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Sometimes send to img2img/inpainting/extras successfully sends the image, but doesn't take you to the destination tab.

### Steps to reproduce the problem

I have no idea, it seems random to me at the moment.

### What should have happened?

The correct tab should be activated.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/8b8a9633520efff0abcee85e0268c2b358f77566

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui
embedding-inspector
sd-dynamic-prompts
sd-dynamic-thresholding
sd-webui-controlnet
sd-webui-model-converter
stable-diffusion-webui-Prompt_Generator
stable-diffusion-webui-anti-burn
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
.
```

**Comment by anapnoe** [comment]
it does happen in Firefox sometimes there is no error in the logs this seems to be browser specific the click event doesn't always fire

**Comment by MakingMadness** [comment]
Weird! Anything I can do to help diagnose?

**Comment by SirVeggie** [comment]
I have the same issue on Brave (Windows). Seems like the first time I click `send to inpaint` it switches the tab, but the following times it will never change the tab again.
