### ISSUE TITLE
[Bug]: There's a strange bar at the bottom of inpainting

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

This is on the normal inpainting tab:

![image](https://user-images.githubusercontent.com/116045189/229248110-2a9bd66a-ba34-4b54-b396-5a2a3b5bba1d.png)

It has a white button on it that doesn't seem to do anything. I don't know how it appeared but the inspector gives this:

```
<div class="spl-footer" style=""><div class="spl-title"> </div><div class="spl-description"> </div><div class="spl-button"> </div></div>
```

It blocks you from being able to paint the bottom of the image.

### Steps to reproduce the problem

No idea.

### What should have happened?

No idea.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/8b8a9633520efff0abcee85e0268c2b358f77566

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui
embedding-inspector
sd-dynamic-prompts
sd-dynamic-thresholding
sd-webui-controlnet
sd-webui-model-converter
stable-diffusion-webui-Prompt_Generator
stable-diffusion-webui-anti-burn
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
Nothing.
```

**Comment by MakingMadness** [comment]
It seems to be related to javascript/spotlight.js

It goes away if you import a generated image to inpainting.

**Comment by anapnoe** [comment]
Firefox 111.0.1 (64-bit) windows 10 doesn't show any issues this shouldn't be visible update your browser 
spoiler: this area is planned to be used to display the info for the generated images for the modal preview view

**Comment by MakingMadness** [comment]
That's the one I'm on. If it's a WIP then I guess no big deal :)

I look forward to seeing this!
