### ISSUE TITLE
[Bug]: Can't inpaint top of image, toolbar is in the way

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://user-images.githubusercontent.com/116045189/229250039-b69b2fdd-464d-4f43-9139-400e71b03790.png)

### Steps to reproduce the problem

Try to inpaint the top of an image.

### What should have happened?

Toolbar doesn't overlap with the image.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/8b8a9633520efff0abcee85e0268c2b358f77566

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui
embedding-inspector
sd-dynamic-prompts
sd-dynamic-thresholding
sd-webui-controlnet
sd-webui-model-converter
stable-diffusion-webui-Prompt_Generator
stable-diffusion-webui-anti-burn
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
.
```

### Additional information

It's possible to work around this by clicking on the fullscreen button.

**Comment by falsonerd** [comment]
You can move the image around by clicking on the move tool and click'n'drag.

**Comment by MakingMadness** [comment]
Thanks, I didn't know that! In which case why don't we make this a feature request instead? :)
