### ISSUE TITLE
[Feature Request]: CivitAI Extension Compatability

### ISSUE THREAD

**Issue by Pixl64** [anapnoe/stable-diffusion-webui-ux#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

In the standard build of the Web UI, there are 3 extra buttons on each 'Extra Network'. These link to the model's page, and you can automatically input prompts to the input using them. However, these don't show on Web UX.

I find the extension quite useful when using LORAs, so it would be great if it could be implemented

It should look like this:
![image](https://user-images.githubusercontent.com/85389249/229305522-60035572-25eb-4c0e-ae9e-ba256b9e099a.png)

### Proposed workflow

1. Click 'Extra Networks' 
2. Hover over an item
3. Click the buttons

### Additional information

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper
Link to the extension page

It also has a view for thumb view, but I assume that UX uses cards as they look better so it wouldn't be necessary to implement those 
![image](https://user-images.githubusercontent.com/85389249/229305634-cad59866-91c0-4ba4-b196-359cc9f99d16.png)

**Comment by anapnoe** [comment]
you can click on the update CivitAI blue button next to extra networks search area to display the icon buttons shown in the pictures

**Comment by boudyisnoob** [comment]
> you can click on the update CivitAI blue button next to extra networks search area to display the icon buttons shown in the pictures

hello there, I couldn't find that button you mentioned, although I have the CivitAi extension installed 
![image](https://github.com/anapnoe/stable-diffusion-webui-ux/assets/113399517/a5e6529e-c03b-492e-ac64-ac492131186f)
only the default refresh button which doesn't add the CivitAi buttons

**Comment by pessivesto** [comment]
we need to this button!!!

**Comment by boudywho** [comment]
> we need to this button!!!

hey, I no longer use webui-ux, but I found [this](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper) extension (which is a fork from CivitAI helper), it has a setting to always show these buttons without pressing refresh, I had this problem (on another webui) and basically fixed it with this
