### ISSUE TITLE
[Bug]: Inpainting errors, but returns the same image instead of displaying the error.

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When this occurs, inpainting will refresh the image as if it's completed the generation, but it simply returns the same image that it last generated. Looking in the consoles there are errors.

### Steps to reproduce the problem

I'm not sure exactly, it doesn't always happen. I feel like it might be related to importing from PNG Info somehow?

### What should have happened?

A new image should be returned, or an error should be displayed.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/b8d208fa69efaa4559347c92b55f22ac79fdd1af

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui
embedding-inspector
sd-dynamic-prompts
sd-dynamic-thresholding
sd-webui-controlnet
sd-webui-model-converter
stable-diffusion-webui-Prompt_Generator
stable-diffusion-webui-anti-burn
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
### Web Console


Uncaught (in promise) API Error 6
XHRPOSThttp://xxx.xxx.xxx.xxx:7860/run/predict/
[HTTP/1.1 500 Internal Server Error 3ms]

	
POST
	
scheme
	http
host
	xxx.xxx.xxx.xxx:7860
filename
	/run/predict/
Address
	xxx.xxx.xxx.xxx:7860
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred158 B (14 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest

	
content-length
	14
content-type
	application/json
date
	Sun, 02 Apr 2023 23:49:22 GMT
server
	uvicorn
	
Accept
	*/*
Accept-Encoding
	gzip, deflate
Accept-Language
	en-US,en;q=0.5
Connection
	keep-alive
Content-Length
	865494
Content-Type
	application/json
Host
	xxx.xxx.xxx.xxx:7860
Origin
	http://xxx.xxx.xxx.xxx:7860
Referer
	http://xxx.xxx.xxx.xxx:7860/
User-Agent
	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0

Uncaught (in promise) API Error 
```

### Terminal

```
Apr 03 00:47:45 xxx webui.sh[1910947]: Traceback (most recent call last):
Apr 03 00:47:45 xxx webui.sh[1910947]:   File "/home/xxx/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
Apr 03 00:47:45 xxx webui.sh[1910947]:     output = await app.get_blocks().process_api(
Apr 03 00:47:45 xxx webui.sh[1910947]:   File "/home/xxx/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1013, in process_api
Apr 03 00:47:45 xxx webui.sh[1910947]:     inputs = self.preprocess_data(fn_index, inputs, state)
Apr 03 00:47:45 xxx webui.sh[1910947]:   File "/home/xxx/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 911, in preprocess_data
Apr 03 00:47:45 xxx webui.sh[1910947]:     processed_input.append(block.preprocess(inputs[i]))
Apr 03 00:47:45 xxx webui.sh[1910947]:   File "/home/xxx/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 1488, in preprocess
Apr 03 00:47:45 xxx webui.sh[1910947]:     assert isinstance(x, dict)
Apr 03 00:47:45 xxx webui.sh[1910947]: AssertionError
```

### Additional information

We could really use some better error feedback, maybe the errors can be displayed somewhere in the UI?. This would be especially relevant if you're on mobile and can't check the terminal. I'll make a new issue for it actually.

**Comment by anapnoe** [comment]
no one else commented and it has been 3 weeks I will close the issue feel free to reopen it if it hasn't been fixed
