### ISSUE TITLE
[Bug]: PNGs not shown as supported files

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

At least in Linux, when uploading an image to the interface, PNGs are not among the allowed filetypes.

### Steps to reproduce the problem

.

### What should have happened?

![image](https://user-images.githubusercontent.com/116045189/229826712-e985465a-40f0-4924-b7c7-96b49d69e9be.png)

All supported types should include PNG.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/b8d208fa69efaa4559347c92b55f22ac79fdd1af

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
.
```

### List of extensions

.

### Console logs

```Shell
.
```

**Comment by anapnoe** [comment]
can you test the dev branch? 
this bug is coming from gradio image component in gradio 3.23.0 it has been fixed
