### ISSUE TITLE
[Bug]: Posex Extension issue

### ISSUE THREAD

**Issue by falsonerd** [anapnoe/stable-diffusion-webui-ux#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After hovering mouse of resolution params textfield disappears...
After extension is loaded.
![image](https://user-images.githubusercontent.com/50148645/230751862-81e76afd-7b47-4d3c-85d4-aa9364e04621.png)
After hovering mouse over the text/inputfields
![image](https://user-images.githubusercontent.com/50148645/230751887-74a98ed1-3119-4cf7-b5d9-65fdc005fffe.png)

PS: Using Posex extension at commit 233daf as latest commits doesn't seem to to work with ux webui.

### Steps to reproduce the problem

1. Start WEBUI
2. Activate Posex by checking send to controlnet
3. Hover your mouse of input fields in •Canvas Size•

### What should have happened?

Be able to input text properly.

### Commit where the problem happens

.

### What platforms do you use to access the UI ?

Other/Cloud

### Command Line Arguments

```Shell
--no-half-vae --xformers --enable-insecure-extension-access --no-hashing --lowram --gradio-queue --autolaunch
```

### List of extensions

<html>
<body>

Extension | URL | Version | Update
-- | -- | -- | --
AdditionalNetwork | https://github.com/kohya-ss/sd-webui-additional-networks | d944d428 (Thu Apr 6 10:42:19 2023) | unknown
Batch-links | https://github.com/etherealxx/batchlinks-webui | fceda4d6 (Thu Mar 30 11:13:00 2023) | unknown
Controlnet | https://github.com/Mikubill/sd-webui-controlnet | 241c05f8 (Thu Mar 23 15:18:35 2023) | unknown
Controlnet-Depth-lib | https://github.com/jexom/sd-webui-depth-lib | 28a22387 (Mon Mar 6 21:02:28 2023) | unknown
Dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts | 707fa9a1 (Thu Apr 6 18:31:57 2023) | unknown
HuggingFace | https://github.com/camenduru/stable-diffusion-webui-huggingface | 6e824a1a (Tue Feb 28 20:53:14 2023) | unknown
Images-Browser | https://github.com/AlUlkesh/stable-diffusion-webui-images-browser | 1d5c2e75 (Tue Mar 28 13:19:52 2023) | unknown
Locon | https://github.com/KohakuBlueleaf/a1111-sd-webui-locon | 85a1443c (Sat Apr 8 07:41:57 2023) | unknown
Lora-block-weight | https://github.com/hako-mikan/sd-webui-lora-block-weight | 3b8caf15 (Fri Apr 7 16:47:47 2023) | unknown
Mbw | https://github.com/bbc-mc/sdweb-merge-block-weighted-gui | 8a62a753 (Thu Jan 19 21:31:06 2023) | unknown
Model-Converter | https://github.com/Akegarasu/sd-webui-model-converter | d19e2816 (Sun Mar 26 06:36:49 2023) | unknown
Model-toolkit | https://github.com/arenatemp/stable-diffusion-webui-model-toolkit | d20eb4ec (Mon Apr 3 09:30:33 2023) | unknown
Posex | https://github.com/hnmr293/posex | 233daf8e (Tue Mar 7 12:21:57 2023) | unknown
Stealth-pnginfo | https://github.com/ashen-sensored/sd_webui_stealth_pnginfo | 6729fcea (Thu Apr 6 08:05:13 2023) | unknown
Supermerger | https://github.com/hako-mikan/sd-webui-supermerger | ba775c89 (Fri Apr 7 15:40:24 2023) | unknown
Tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git | 223abf54 (Wed Apr 5 11:05:44 2023) | unknown
Two-shot-Composable-Lora | https://github.com/opparco/stable-diffusion-webui-composable-lora | d4963e48 (Mon Feb 27 17:40:08 2023) | unknown
Webui-Tunnels | https://github.com/camenduru/sd-webui-tunnels | 709b8a01 (Fri Mar 31 13:19:35 2023) | unknown
sd-civitai-browser | https://github.com/camenduru/sd-civitai-browser | 0a5aec60 (Mon Apr 3 17:40:41 2023) | unknown

</body>
</html>

### Console logs

```Shell
No errors
```

### Additional information

**Openpose Editor** extension also makes webui takes a tad bit longer to load after accessing the page, from a max of 10s to 1min+

**Comment by anapnoe** [comment]
this issue is related to option setting `Dispatch event change on release, for slider and input number components` the posex extension uses its own gui and doesn't follow gradio's ui components structure I fix it for now but maybe other extensions that don't create the gui from gradio components will have similar issue in that case uncheck the related option setting
