### ISSUE TITLE
[Bug]: Unable to filter additional networks by subfolder

### ISSUE THREAD

**Issue by norazlan-dev** [anapnoe/stable-diffusion-webui-ux#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Unable to filter additional networks by subfolder

### Steps to reproduce the problem

1. Go to additional networks, embeddings in my case
2. Press negative prompt subfolder
3. No response/not filtered

![image](https://user-images.githubusercontent.com/102639075/230810236-5567cc02-23e4-44ee-87ac-46f45f01d520.png)

### What should have happened?

Only embeddings that are inside the selected subfolder should be shown.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/3d457a06be7020b08beb23d010e8e0ed823c97a9

### What platforms do you use to access the UI ?

Windows, Other/Cloud

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --enable-insecure-extension-access --api --deepdanbooru --theme=dark --share
```

### List of extensions

<html><body>

Extension | URL | Version | Update
-- | -- | -- | --
StylePile | https://github.com/some9000/StylePile | 206b3d06 (Sun Apr 2 18:29:13 2023) | unknown
a1111-sd-webui-locon | https://github.com/KohakuBlueleaf/a1111-sd-webui-locon | 85a1443c (Sat Apr 8 07:41:57 2023) | unknown
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete | 223abf54 (Wed Apr 5 11:05:44 2023) | unknown
sd-webui-additional-networks | https://github.com/kohya-ss/sd-webui-additional-networks | d944d428 (Thu Apr 6 10:42:19 2023) | unknown
sd-webui-ar | https://github.com/alemelis/sd-webui-ar | 4ac84484 (Thu Mar 30 19:42:57 2023) | unknown
sd_webui_stealth_pnginfo | https://github.com/camenduru/sd_webui_stealth_pnginfo | 9a8709a7 (Sat Apr 1 20:36:03 2023) | unknown
stable-diffusion-webui-images-browser | https://github.com/AlUlkesh/stable-diffusion-webui-images-browser | 2cba040f (Sun Apr 9 23:23:17 2023) | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 | 0a3d03a4 (Tue Feb 7 06:07:23 2023) | unknown
LDSR | built-in |   |  
Lora | built-in |   |  
ScuNET | built-in |   |  
SwinIR | built-in |   |  
prompt-bracket-checker | built-in |   |  
sd_theme_editor | built-in |   |  

</body>
</html>

### Console logs

```Shell
No error log
```

**Comment by anapnoe** [comment]
Thanks for your feedback it has been fixed :)
