### ISSUE TITLE
[Feature Request]: Click to zoom image

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

It would be great to be able to fullscreen an image like in vanilla so you can take a closer look.

### Proposed workflow

1. Click the image.
2. See a bigger image!

**Comment by MakingMadness** [comment]
Also being able to pinch-zoom on the enlarged image to explore details on mobile would be great!

**Comment by anapnoe** [comment]
This should be working  on chrome and Firefox I have no idea about Edge you should at least install another browser to cross reference the issues Edge support would come on a later stage best regards

**Comment by MakingMadness** [comment]
Love it, nicely done! :heart_eyes:

Sure thing, I'll check it in Firefox next time.
