### ISSUE TITLE
[Bug]: When clicking generate forever, the previous image immediately disappears

### ISSUE THREAD

**Issue by SirVeggie** [anapnoe/stable-diffusion-webui-ux#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When clicking generate, the previous image immediately disappears. I like to look at the previous image while the next image is generating. This is especially bad with "generate forever", where the image appears for a split second only as the next generation starts immediately.

### Steps to reproduce the problem

-

### What should have happened?

The previous image should stay until replaced by either a live preview or a new image.

### Commit where the problem happens

2ac62ce241396939c387a221e20b0a7a8c399b6f

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--xformers
```

### List of extensions

No

### Console logs

```Shell
nothing strange
```

**Comment by SirVeggie** [comment]
I don't have live previews on, it simply shows a blank space while generating.

**Comment by anapnoe** [comment]
did you use batch count or batch size ?
-batch count will generate each image separate so while the next image is generated the previous image is visible this is the behavior what you want
-batch size generates all images in one go it uses more vram and you have no preview until the end of the process
-generate forever has the issue you describe if you want a remedy for it you can use the batch count with max size
or if you don't use live preview at all you can write this line to the user.css file, if it doesn't exist create the file at the root of stable diffusion-webui
`.livePreview{display:none;}`
I will fix it in the next release

**Comment by SirVeggie** [comment]
I don't really use live preview these days anymore, so the `.livePreview{display:none;}` hotfix worked great, thanks! This webui is a much better user experience than the original one, so thanks for that too.

Quick off-topic: using loras slows down the generation speed in the older version (this repo) of the webui, so it would be nice to see it updated to latest version whenever possible (where using loras does not seem to affect gen speeds).

**Comment by SirVeggie** [comment]
Works as expected, sorry for slow close.
