### ISSUE TITLE
[Bug]: Extra network cards overflow when folder buttons have multiple rows

### ISSUE THREAD

**Issue by SirVeggie** [anapnoe/stable-diffusion-webui-ux#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://user-images.githubusercontent.com/32365239/231888303-d84d6bd3-afce-41ac-a026-ffa0e24497d0.png)

Last row of cards is missing the names since the container overflows off-screen:

![image](https://user-images.githubusercontent.com/32365239/231888382-cb7c23d6-37e8-4156-b9c6-01795d8bc9b0.png)

Modified this line in css to fix it temporarily:

![image](https://user-images.githubusercontent.com/32365239/231888583-e361a6c6-ee00-4cd7-aa45-5978f8543052.png)

### Steps to reproduce the problem

-

### What should have happened?

Network card container size needs to take into account the size of folder button container.

### Commit where the problem happens

2ac62ce241396939c387a221e20b0a7a8c399b6f

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
-
```

### List of extensions

-

### Console logs

```Shell
-
```

**Comment by anapnoe** [comment]
I am thinking to change the buttons with a dropdown selection that will not affect the layout height 
an other solution would be to get the height from subdirs and subtract from the grid overflow div but this will not work if you have 100 categories and the height of the subdirs is greater than the grid overflow

**Comment by SirVeggie** [comment]
Dropdown would work, but it's much slower to navigate than buttons so I'm a quite hesitant to use it for those edge cases. Most optimal would be to have it switch dynamically depending on the amount, but that seems a bit too ambitious.

Another option could be to include the buttons into the scroll area itself, so they can scroll out of view.

**Comment by anapnoe** [comment]
yep I will do it this way I will include the buttons to the overflow container
