### ISSUE TITLE
[Feature Request]: Make the Lora/Checkpoint able to scale

### ISSUE THREAD

**Issue by Hakim3i** [anapnoe/stable-diffusion-webui-ux#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hello
I would like to be able to drag the panel and make it bigger because so many lora and checkpoints.
Maybe able to chose the size of the picture as well.
![image](https://user-images.githubusercontent.com/11870227/232208279-2dad3981-cc52-411b-8409-103573eb97e9.png)
Thank you for your work.

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by anapnoe** [comment]
You are welcome Hakim, you can change the size of the card from settings -> Extra Networks -> Card size for extra networks

**Comment by Hakim3i** [comment]
That's a good one but still I would like to be able to resize the panel for more space would be nice

**Comment by anapnoe** [comment]
if you want to use o hotfix for now you can add this to the user.css file located in root folder if doesn't exist create and add this  
```
[id$="2img_extra_networks_row"].aside {
    max-width: 50%;
    min-width: 320px;
}
```

**Comment by Hakim3i** [comment]
omg much better now thanks

**Comment by Neverdusk** [comment]
> if you want to use o hotfix for now you can add the code below to the user.css file located in root folder if it doesn't exist create it the extra networks aside view will cover 50% of the available screen width feel free to adjust it to your liking
> 
> ```
> [id$="2img_extra_networks_row"].aside {
>     max-width: 50%;
>     min-width: 320px;
> }
> ```

Would it be possible to do something similar, but for the extra network categories? I have a ton of folders and sub-folders for LORAs, and they only leave a few inches of space to see the actual LORA cards in the UI. Being able to slide the category-card border up or down would definitely help.

**Comment by anapnoe** [comment]
it has been fixed scrolling container includes the folder buttons as well
