### ISSUE TITLE
[Feature Request]: make it easier to work with network filter textbox

### ISSUE THREAD

**Issue by halr9000** [anapnoe/stable-diffusion-webui-ux#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Here are some ideas to make it easier to work with the filtering of networks which might be useful when you have hundreds installed. (I have 275 at the moment.)

- ESC clears input when network filter box is focused and contains text
- ESC when filter is empty closes networks flyout
- Add a "clear input" or "x" button in/near the network filter box (clicking it will clear the filter)
![Screenshot 2023-04-17 074003](https://user-images.githubusercontent.com/18482/232477192-251a4eb0-8678-45ce-afbd-abaa148dd597.png)

### Proposed workflow

1. Click the networks flyover button
2. Type a filter
3. Click ESC or "x" button to clear it so that you can begin typing another
4. When done working with networks, click ESC again to close the flyover

**Comment by anapnoe** [comment]
Thank you very much for your support @halr9000
