### ISSUE TITLE
[Feature Request]: colab version?

### ISSUE THREAD

**Issue by annasophiachristianahahn** [anapnoe/stable-diffusion-webui-ux#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Has anyone made a colab version yet?

### Proposed workflow

Google colab

**Comment by anapnoe** [comment]
@Linaqruf has made one
https://colab.research.google.com/github/Linaqruf/sd-notebook-collection/blob/main/cagliostro-colab-ui.ipynb
