### ISSUE TITLE
[Bug]: Install in linux broken due to webui.sh

### ISSUE THREAD

**Issue by tdtrumble** [anapnoe/stable-diffusion-webui-ux#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

It looks like webui.sh was reverted to the file from the master auto1111 branch, so when you run the install directions for linux in the readme, it just installs the auto1111 repo. 

Line 151:
    "${GIT}" clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git "${clone_dir}"

### Steps to reproduce the problem

Follow directions under "Automatic Installation on Linux" in readme

Automatic Installation on Linux
Install the dependencies:
# Debian-based:
sudo apt install wget git python3 python3-venv
# Red Hat-based:
sudo dnf install wget git python3
# Arch-based:
sudo pacman -S wget git python3
To install in /home/$(whoami)/stable-diffusion-webui/, run:
bash <(wget -qO- https://raw.githubusercontent.com/anapnoe/stable-diffusion-webui-ux/master/webui.sh)
Run webui.sh.

### What should have happened?

Should have installed the https://github.com/anapnoe/stable-diffusion-webui-ux repo

### Commit where the problem happens

n/a

### Command Line Arguments

```Shell
n/a
```

### List of extensions

n/a

### Console logs

```Shell
n/a
```

**Comment by anapnoe** [comment]
thank you
