### ISSUE TITLE
[Feature Request]: Prompt Textbox Keyboard functionality

### ISSUE THREAD

**Issue by AsuraAce** [anapnoe/stable-diffusion-webui-ux#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

At the moment the only thing i can do with the keyboard within the prompt boxes, is to increase the weight. I can´t even use the arrow keys to move the curser. let alone copy paste. pretty much have to use the mouse for everything.

this actually true for all text elements not only the prompt boxes.

### Proposed workflow

unlock the textbox please

### Additional information
tried different browser because i thought this may be a bug, same result.

_No response_

**Comment by anapnoe** [comment]
Tested on Chrome and Mozilla browser latest versions Win10 works as expected

**Comment by anapnoe** [comment]
this is strange I just tested it on Brave too `dev ` and  `stable`  branch have no issues I have no idea why this isn't working for you but I am confident that it has nothing to do with the ui-ux

**Comment by AsuraAce** [comment]
Problem was caused by an extension. (don´t know which one, will try to figure that out tomorrow). That said, there are quite a lot of extensions that either are not working or are break things. I´ll let you know tomorrow or in the coming days.
