### ISSUE TITLE
[Bug]: how do I perform an SD Upscale OR ultimate SD upscale 

### ISSUE THREAD

**Issue by annasophiachristianahahn** [anapnoe/stable-diffusion-webui-ux#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Is there a way to run SD upscale/Ultimate SD upscale scripts from automatic1111? If so how would I do ao

### Steps to reproduce the problem

Look inside scripts menu

### What should have happened?

Sd upscale/ultimate sd upscale should be present?

### Commit where the problem happens

Colab version

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
No
```

### List of extensions

Nothing added

### Console logs

```Shell
Na
```

**Comment by AsuraAce** [comment]
try the img2img tab, should be there in the script section. it is not in the script section for txt2img
