### ISSUE TITLE
[Bug]: In Checkpoint Merger, merging a model gives no feedback

### ISSUE THREAD

**Issue by MakingMadness** [anapnoe/stable-diffusion-webui-ux#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://user-images.githubusercontent.com/116045189/226075302-866aa4de-09ce-4a6c-847b-5ffa93dac4a9.png)

The checkpoint didn't appear, so presumably there was an error, but what is it?

### Steps to reproduce the problem

1. Go to Checkpoint Merger
2. Select checkpoints
3. Click Merge

### What should have happened?

Some feedback about what happened should appear.

### Commit where the problem happens

https://github.com/anapnoe/stable-diffusion-webui-ux/commit/d812736d6e32879a164b9a18da325dbe9cce3824

### What platforms do you use to access the UI ?

Linux

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention
```

### List of extensions

SD-latent-mirroring
StylePile
deforum-for-automatic1111-webui
embedding-inspector
sd-dynamic-prompts
sd-dynamic-thresholding
sd-webui-controlnet
sd-webui-model-converter
stable-diffusion-webui-Prompt_Generator
stable-diffusion-webui-anti-burn
stable-diffusion-webui-artists-to-study
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-two-shot
ultimate-upscale-for-automatic1111

### Console logs

```Shell
None.
```

**Comment by anapnoe** [comment]
it has been fixed thank you for your feedback
