### ISSUE TITLE
[Bug]: It is hard to open/unfold any embeded outlinebox (tab) on UI

### ISSUE THREAD

**Issue by blueball81** [anapnoe/stable-diffusion-webui-ux#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

With the recent build (a7be020), it is almost impossible to open/unfold any embeded outlinebox(or tab) on main UI.

For example, in the following images, 'Dynamic Prompt' box can be opened or closed by clicking on anywhere on the title.
However, the embeded boxes, such as 'Prompt Magic', 'Need Help?', etc., cannot be opened or closed by clicking the title title box. After lots of trials, I found that I can open it by clicking at the edge of the title boxes.  But this should work same as the mother box.

It would be nice to check and correct this issue.

Thanks.

![image](https://user-images.githubusercontent.com/1153785/234039452-0b153d60-573f-4364-b258-97ecd1b65660.png)

### Steps to reproduce the problem

1. Go to main UI, and find any extensions that has embeded foldable tab/boxes
2. Click on the title of the embeded tabs/boxes to open/unfold the box. 
3. It does not open. Instead clicking on the title box, it can be opened by clicking the edge of the box title.

### What should have happened?

(explained above)

### Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a7be020c2a21aa51bd6b7b0b51a997bb07b07974

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --gradio-queue --enable-insecure-extension-access --listen --autolaunch --theme dark
```

### List of extensions

n/a

### Console logs

```Shell
n/a
```

**Comment by anapnoe** [comment]
not tested on nested accordions nice finding I will fix it thanks
