### ISSUE TITLE
[Bug]: drop-down option menu I don't feel as good as before

### ISSUE THREAD

**Issue by devioa** [anapnoe/stable-diffusion-webui-ux#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

1. In `Styles` option, I can't select the first one, but I can click near bottom the first option to select.
![1](https://user-images.githubusercontent.com/38558065/234046761-0957c106-5248-4108-a6ff-8fd85b1fb046.png)
2. Text line wrap, I don't like line wrap, I would rather the overflowing text be hidden than seeing tabs of varying heights.
![2](https://user-images.githubusercontent.com/38558065/234046776-421b0765-eb20-4e57-abeb-f0c9c47cd3b1.png)
And last, the `Script` option menu when mouse hover on it will become a text input cursor. But that can not input text actually.
Oh, I almost forgot to say, I remember the thumbnail at the bottom used to be centered, but now it has on left particularly.
![4](https://user-images.githubusercontent.com/38558065/234055780-df21dd91-9dea-405b-a28d-e23cbc04a6de.png)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

I've tried locally restore from previous commits but failed. Because I'm not very familiar with CSS.
I really like your work. this WebUI design is very brilliant.
If possible, I would like you to restore the drop-down option menu to its previous state.
If can't, could you please tell me what I need to modify in style.css to restore it?
Thank you very much.

### Commit where the problem happens

a7be020c2a21aa51bd6b7b0b51a997bb07b07974

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

**Comment by anapnoe** [comment]
yes I plan to restore dropdown menu functionality at least for the single select ones gradios new dropdown menu is problematic

**Comment by devioa** [comment]
> yes I plan to restore dropdown menu functionality at least for the single select ones gradios new dropdown menu is problematic I will fix the thumbnail thanks

Thanks for your work

**Comment by TheFairyMan** [comment]
I don't want to open a new issue in case this was related, does the new update to the dropdown menu turn them into tiny dropdowns?
Now every dropdown menu only displays 7 options and always starts at the top, for the checkpoints dropdown menu it only displays 6 at a time now also starting from the top, having quite a lot of time having to scroll to find the model I want.

I'm not sure in which commit it became like that since when I updated there was quite a lot to pull.

**Comment by anapnoe** [comment]
welcome to new gradio 3.23.0 yes unfortunately one of the reasons I didn't updrage for almost a month now waiting for gradio to fix things that were fine but now they aren't anyway I will do my best to fix it until then you can go back to this commit 
7193fb06c4a61ea33ed8169c8a5a442364075c0d
