### ISSUE TITLE
[Bug]:  Inpainting Source picture gets destroyed when pressing Escape Button

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Inside i2i, sketch,inpainting, inpaint sketch. If you have image inside the "Image Source" tab and you full screen any image from the viewport. After doing so the "Image source" will vanish but also locking out the ability to add anymore image into Image Source

### Steps to reproduce the problem

1. Go to .... image2image
2. Press ....inpaint insert image source and generate any picture
3. Click to fullscreen image that is generated.
4. Image in image source goes missing and unable to load anymore images into Image Source

### What should have happened?

image source should still be there and you're able to add a new source in.

### Commit where the problem happens

Latest

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### List of extensions

a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | ce584a0f (Sun Apr 23 14:50:56 2023) | unknown
multidiffusion-upscaler-for-automatic1111 | https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git | f3d79a47 (Sat Apr 15 17:29:10 2023) | unknown
sd-extension-system-info | https://github.com/vladmandic/sd-extension-system-info.git | cc86ce88 (Thu Apr 20 03:53:09 2023) | unknown
sd-webui-3d-open-pose-editor | https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git | f2d5aac5 (Sat Apr 15 13:21:06 2023) | unknown
sd-webui-additional-networks | https://github.com/kohya-ss/sd-webui-additional-networks.git | 2417bee6 (Sat Apr 22 09:31:55 2023) | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | c5984671 (Mon Apr 24 05:51:43 2023) | unknown
sd-webui-supermerger | https://github.com/hako-mikan/sd-webui-supermerger.git | 847c8760 (Fri Apr 21 16:44:01 2023) | unknown
sd_dreambooth_extension | https://github.com/d8ahazard/sd_dreambooth_extension.git | 926ae204 (Fri Mar 31 15:12:45 2023) | unknown
stable-diffusion-webui-dataset-tag-editor | https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor.git | c1c78f59 (Sun Apr 2 11:15:32 2023) | unknown
ultimate-upscale-for-automatic1111

### Console logs

```Shell
nothing unusual in the terminal
```

### Additional information

https://imgur.com/a/RPAzQ6k

Just get this after this happens and unable to add any new source even remove

**Comment by anapnoe** [comment]
can you disable all the inbuild extensions and report back ?

**Comment by rushuna86** [comment]
still exactly the same issue, even cloned a brand new clean install. with nothing but defaults from install process and it still does it. was working fine last night at 4589dbe. but im checking now if it was because let gradio updated  to 3.23. I been using 3.16.2 for months now because I changed requirements in there for dreambooth to run torch 2, will check this now.

**Comment by rushuna86** [comment]
sorry can't be much help but last commit that work was previously mentioned. also this also changed in not sure which of the commit https://imgur.com/a/bbfbOjA where that white area showed up.

**Comment by rushuna86** [comment]
I found the issue...... so if you go fullscreen and press the X button the close full screen all goes well. but if you press "esc" button on keyboard to exit. it triggers it.....

**Comment by anapnoe** [comment]
yes I can confirm that the esc triggers the destroy event of the instance component can you change the title now that we have spotted the issue I can fix it thanks
