### ISSUE TITLE
[Bug]: Certain Text inside UI is almost unreadable

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

One of the commits after 4589dbe, been having problems with it for days now and went through eveyr single option in theme edittor and there wasn't one. But text like generation info is a very dark grey color and on every dark theme it's pretty much unreadable. Only found out that if I ran it with the arguement --theme dark it changes this text to white and marks it readable again. Screenshot are made with and without the --theme dark using "moonlight.css"

### Steps to reproduce the problem

https://imgur.com/a/Zygd05l

### What should have happened?

Text should be still visible.

### Commit where the problem happens

Problem came up after 3db4fbf or a7be020

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### List of extensions

built-in

### Console logs

```Shell
no errors
```

### Additional information

Tried with built-in no plugin clean install. Text only visible if you turn on --theme dark

**Comment by rushuna86** [comment]
Sorry before hand if this isn't a bug and I'm just dumb, but it was all visible before those commits

**Comment by anapnoe** [comment]
it is caused by windows settings > colors > choose your color > `Light ` option if you set it to `Dark ` issue is resolved
I will fix it thanks

**Comment by rushuna86** [comment]
thank you

**Comment by anapnoe** [comment]
you are welcome
