### ISSUE TITLE
[Bug]: blob drawing missing in latent couple 

### ISSUE THREAD

**Issue by annasophiachristianahahn** [anapnoe/stable-diffusion-webui-ux#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hello! This is in reference to Vlad’s UI

I see that by default the UI includes the latent couple extension
https://github.com/miZyind/sd-webui-latent-couple/blob/main/README.md

However I only see the rectangular mode for dividing the canvas- how can I access the ‘blob drawing’ interface where you can actually draw the shapes of the regions you would like to prompt?

when I try to install the extension it says that the extension is already present…. is there a way that I can make it function fully with the prompt region drawing feature? Is there a way for me to uninstall the current version and replace it with the extension that includes drawing? I am using the colab implementation of Vlad’s UI if that’s relevant 

### Steps to reproduce the problem

Go to latent couple extension

### What should have happened?

There should be drawing option in addition to rectangular division option

### Commit where the problem happens

All

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

Standard

### Console logs

```Shell
NA
```

**Comment by anapnoe** [comment]
install it from here https://github.com/ashen-sensored/stable-diffusion-webui-two-shot
and maybe next time ask in discussions cause issues here are specific to the ui-ux 
and once they are closed not many people search for invalid questions in closed issues

**Comment by annasophiachristianahahn** [comment]
Thank you! When I install it from that url I get the message AssertionError: Extension directory already exists: /content/cagliostro-colab-ui/extensions/stable-diffusion-webui-two-shotHow can I fix this?Thank you so much!On Apr 26, 2023, at 1:01 PM, anapnoe ***@***.***> wrote:﻿
install it from here https://github.com/ashen-sensored/stable-diffusion-webui-two-shot
and maybe next time ask in discussions cause issues here are specific to the ui-ux
and once they are closed not many people search for invalid questions in closed issues

**Comment by annasophiachristianahahn** [comment]
Ok I managed to successfully install the extension- however it does not appear in the UI even after applying and restarting the UI…

I tried deactivating the original version of the extension also- but this does not make the new version of the extension appear in the UI

what can I do to force the UI to show the new forked version of the extension that has been installed?
![IMG_2473](https://user-images.githubusercontent.com/26853395/234799628-faff9d7e-bac3-4b27-938f-e6db6647a023.jpeg)
![IMG_2476](https://user-images.githubusercontent.com/26853395/234799671-4721055a-5c77-488b-b569-ef90bf03edad.jpeg)

![IMG_2474](https://user-images.githubusercontent.com/26853395/234799616-7c5706f6-1269-4701-9bd9-f0a21156f821.jpeg)
