### ISSUE TITLE
[Bug]: Buttons that reload UI don't seem to be working

### ISSUE THREAD

**Issue by PaulCoddington** [anapnoe/stable-diffusion-webui-ux#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After installing extensions, settings changes, etc, UI cannot be restarted from the web interface.

Changes seem to be applied, but it is necessary to quit both browser and terminal, then relaunch.

### Steps to reproduce the problem

1. Install an extension
2. Click 'Apply and Restart UI'

Also

1. Click 'Restart UI' icon at bottom of txt2img page

Also

1. Change settings
2. Click 'Apply Settings'
3. Click 'Reload UI'

### What should have happened?

Expect UI to be reloaded with new configuration.

### Commit where the problem happens

d812736

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--medvram --no-half-vae --autolaunch
```

### List of extensions

 a1111-sd-webui-locon
 a1111-sd-webui-tagcomplete
 multidiffusion-upscaler-for-automatic1111
 sd-webui-additional-networks
 stable-diffusion-webui-images-browser

Error persists when extra extensions are uninstalled.

### Console logs

```Shell
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Commit hash: d812736d6e32879a164b9a18da325dbe9cce3824
Installing requirements for Web UI

Launching Web UI with arguments: --medvram --no-half-vae --autolaunch
No module 'xformers'. Proceeding without it.
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [6ce0161689] from C:\ProgramData\Stable Diffusion\stable-diffusion-webui-ux\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\ProgramData\Stable Diffusion\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 1.8s (create model: 0.5s, apply weights to model: 0.7s, apply half(): 0.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 10.4s (import gradio: 2.6s, import ldm: 0.9s, other imports: 1.8s, list extensions: 0.6s, load scripts: 1.3s, load SD checkpoint: 2.2s, create ui: 0.5s, gradio launch: 0.3s).
```

### Additional information

Original AUTOMATIC1111 version does not exhibit this issue (identical installation conditions in a parallel subfolder in a separate Miniconda environment).

Not observing any network traffic when reload is attempted. 
Errors appear in devtools:

ui.js?1679132256.0033429:1326 
       Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at restart_reload (ui.js?1679132256.0033429:1326:20)
    at extensions_apply (extensions.js?1679132255.9993432:14:5)
    at eval (eval at <anonymous> (index.4395ab38.js:75:2081), <anonymous>:3:38)
    at index.4395ab38.js:34:32410
    at HTMLButtonElement.<anonymous> (index.4395ab38.js:76:2455)
    at index.4395ab38.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.le (index.4395ab38.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:10:48)
    at index.4395ab38.js:4:1266
restart_reload @ ui.js?1679132256.0033429:1326
extensions_apply @ extensions.js?1679132255.9993432:14
eval @ VM116:3
(anonymous) @ index.4395ab38.js:34
(anonymous) @ index.4395ab38.js:76
(anonymous) @ index.4395ab38.js:4
le @ index.4395ab38.js:4
_ @ Button.svelte:10
(anonymous) @ index.4395ab38.js:4
le @ index.4395ab38.js:4
B @ Button.svelte:9
Promise.then (async)
(anonymous) @ index.4395ab38.js:76
(anonymous) @ index.4395ab38.js:4
le @ index.4395ab38.js:4
_ @ Button.svelte:10
(anonymous) @ index.4395ab38.js:4
le @ index.4395ab38.js:4
B @ Button.svelte:9

**Comment by anapnoe** [comment]
on Chrome and Firefox it is working as expected Edge support would be much later thanks for your feedback
