### ISSUE TITLE
[Bug]: Gradio 3.23.0 dropdown component cutoff 

### ISSUE THREAD

**Issue by Pixl64** [anapnoe/stable-diffusion-webui-ux#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When opening the selection boxes for Preprocessor and Model in the ControlNet Extension, the boxes are cut off by the image box above. 

![image](https://user-images.githubusercontent.com/85389249/234665810-7c4cd552-db95-44b0-8c22-9c0663c200bd.png)
![image](https://user-images.githubusercontent.com/85389249/234665858-f4cc6ffe-d13b-4a24-859c-e0e60389d581.png)
As seen in the images above, placeholders 1 and 2 are not shown in the boxes (they are empty files, but it functions the same with actual models)

The same issue occurs with the preprocessor box as well
![image](https://user-images.githubusercontent.com/85389249/234666032-6019a6f6-c765-4b6b-84fe-26fb53a69f9b.png)

The issue only occurs once you have attempted to upload an image to the box. The image also doesn't show, it just shows the "Start Drawing" off the edge of the box.

**Before uploading image (input boxes work)**
![image](https://user-images.githubusercontent.com/85389249/234668158-dc7a505a-b047-4459-89f4-5ed7ed3953a9.png)
**After uploading image first time (input boxes stop working)**
![image](https://user-images.githubusercontent.com/85389249/234668322-2bc9e66a-5412-43ba-993f-ce2dddc54c43.png)
**After uploading image again (input boxes still don't work)**
![image](https://user-images.githubusercontent.com/85389249/234668464-33c1ec51-defe-475c-b5d0-1937f9781a83.png)

### Steps to reproduce the problem

1. Install ControlNet
2. Open ControlNet dropdown box
3. Select an image in the image box
4. Attempt to select a model or preprocessor

### What should have happened?

The boxes should either have a correct scroll distance, so that the top of the box is the top of the list, or the boxes should overlap above the image box.

### Commit where the problem happens

4b78b656

### What platforms do you use to access the UI ?

_Windows_

### What browsers do you use to access the UI ?

_Opera GX and Google Chrome_

### Command Line Arguments

```Shell
--allow-code --administrator --no-half-vae --autolaunch --api --no-download-sd-model --ckpt-dir D:\\StableDiffusion\\stable-diffusion-webui\\models\\Stable-diffusion --vae-dir D:\\StableDiffusion\\stable-diffusion-webui\\models\\VAE --lora-dir D:\\StableDiffusion\\stable-diffusion-webui\\models\\Lora --embeddings-dir D:\\StableDiffusion\\stable-diffusion-webui\\embeddings --hypernetwork-dir D:\\StableDiffusion\\stable-diffusion-webui\\models\\hypernetworks --ui-config-file D:\\StableDiffusion\\stable-diffusion-webui\\ui-config.json
```

### List of extensions

<html>
<body>

Stable-Diffusion-Webui-Civitai-Helper | https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper | fcf5a27a (Fri Apr 14 05:39:01 2023) | unknown
-- | -- | -- | --
a1111-sd-webui-tagcomplete | https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git | 3b51035c (Fri Apr 21 19:21:21 2023) | unknown
a1111-stable-diffusion-webui-vram-estimator | https://github.com/space-nuko/a1111-stable-diffusion-webui-vram-estimator.git | bf8797a3 (Sun Mar 5 03:42:33 2023) | unknown
booru2prompt | https://github.com/Malisius/booru2prompt.git | 4bd88839 (Wed Nov 23 14:41:10 2022) | unknown
canvas-zoom | https://github.com/richrobber2/canvas-zoom.git | b61ca31e (Tue Apr 25 18:46:40 2023) | unknown
deforum-for-automatic1111-webui | https://github.com/deforum-art/deforum-for-automatic1111-webui.git | b55b9500 (Wed Apr 26 12:28:38 2023) | unknown
openOutpaint-webUI-extension | https://github.com/zero01101/openOutpaint-webUI-extension.git | 5e84d6d5 (Mon Apr 10 23:01:41 2023) | unknown
openpose-editor | https://github.com/fkunn1326/openpose-editor.git | 0b10737e (Wed Apr 12 10:20:59 2023) | unknown
posex | https://github.com/hnmr293/posex.git | 61169d30 (Sat Apr 1 12:28:38 2023) | unknown
sd-dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts.git | a53adac9 (Sun Apr 23 13:28:49 2023) | unknown
sd-model-preview-xd | https://github.com/CurtisDS/sd-model-preview-xd | ec78390b (Thu Apr 20 23:44:52 2023) | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | 93b0f9e1 (Wed Apr 26 03:16:41 2023) | unknown
sd-webui-cutoff | https://github.com/hnmr293/sd-webui-cutoff | 89b90487 (Wed Mar 22 15:47:20 2023) | unknown
sd-webui-depth-lib | https://github.com/jexom/sd-webui-depth-lib.git | efa9f616 (Mon Apr 10 05:27:11 2023) | unknown
sd-webui-gelbooru-prompt | https://github.com/antis0007/sd-webui-gelbooru-prompt.git | 4dbea1df (Fri Apr 7 18:47:44 2023) | unknown
sd-webui-infinite-image-browsing | https://github.com/zanllp/sd-webui-infinite-image-browsing.git | d14cb518 (Wed Apr 26 12:11:35 2023) | unknown
sd-webui-llul | https://github.com/hnmr293/sd-webui-llul.git | 9123f098 (Sat Apr 1 12:52:42 2023) | unknown
sd-webui-regional-prompter | https://github.com/hako-mikan/sd-webui-regional-prompter.git | 7f8ed9db (Thu Apr 20 03:20:11 2023) | unknown
stable-diffusion-webui-Prompt_Generator | https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator.git | 0d4de20f (Fri Mar 17 11:22:15 2023) | unknown
stable-diffusion-webui-composable-lora | https://github.com/opparco/stable-diffusion-webui-composable-lora.git | d4963e48 (Mon Feb 27 17:40:08 2023) | unknown
stable-diffusion-webui-images-browser | https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git | 704e42c1 (Mon Apr 24 13:20:37 2023) | unknown
stable-diffusion-webui-promptgen | https://github.com/AUTOMATIC1111/stable-diffusion-webui-promptgen.git | 84e58b5d (Fri Jan 20 11:15:12 2023) | unknown
stable-diffusion-webui-state | https://github.com/ilian6806/stable-diffusion-webui-state.git | 4cc8fa3c (Tue Apr 11 10:25:08 2023) | unknown
stable-diffusion-webui-text2prompt | https://github.com/toshiaki1729/stable-diffusion-webui-text2prompt.git | c4d8cec1 (Fri Feb 24 08:29:55 2023) | unknown
LDSR | built-in |   |  
Lora | built-in |   |  
ScuNET | built-in |   |  
SwinIR | built-in |   |  
prompt-bracket-checker | built-in |   |  
sd_theme_editor | built-in

</body>

### Console logs

```Shell
Already up to date.
venv "D:\StableDiffusion\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 4b78b6569b960abdc880699ee29f5a01373966f6
Installing requirements for Web UI



Installing sd-dynamic-prompts requirements.txt




Launching Web UI with arguments: --allow-code --administrator --no-half-vae --autolaunch --api --no-download-sd-model --ckpt-dir D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion --vae-dir D:\StableDiffusion\stable-diffusion-webui\models\VAE --lora-dir D:\StableDiffusion\stable-diffusion-webui\models\Lora --embeddings-dir D:\StableDiffusion\stable-diffusion-webui\embeddings --hypernetwork-dir D:\StableDiffusion\stable-diffusion-webui\models\hypernetworks --ui-config-file D:\StableDiffusion\stable-diffusion-webui\ui-config.json
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\StableDiffusion\stable-diffusion-webui-ux\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Loading booru2prompt settings
ControlNet v1.1.112
ControlNet v1.1.112
[text2prompt] Following databases are available:
    all-mpnet-base-v2 : danbooru_strict
Loading weights [099e07547a] from D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\darkSushiMixMix_brighterPruned.safetensors
Creating model from config: D:\StableDiffusion\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\StableDiffusion\stable-diffusion-webui\models\VAE\orangemix.vae.pt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(24): bad-hands-5, bad-image-v2-39000, badhandv4, bad_prompt_version2, bad_quality, easynegative, flame_surge_style, guweiz_style, hurybone_style, iskou_style, lightning_style, mikeou_art, nixeu_basic, nixeu_basic2, nixeu_extra, nixeu_soft, nixeu_white, prt, space_style, splash_style, splash_style2, torino_art, vile_prompt3, wano_style_30100
Model loaded in 9.3s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 4.6s, apply half(): 0.7s, load VAE: 0.9s, move model to device: 1.0s, load textual inversion embeddings: 1.4s).
[VRAMEstimator] No stats available, run benchmark first
*Deforum ControlNet support: enabled*
[text2prompt] Loading database with name "all-mpnet-base-v2 : danbooru_strict"...
[text2prompt] Database loaded
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 29.7s (import torch: 3.1s, import gradio: 1.3s, import ldm: 0.7s, other imports: 1.7s, setup codeformer: 0.1s, load scripts: 3.9s, load SD checkpoint: 9.4s, create ui: 8.9s, gradio launch: 0.5s).
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\main\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\main\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:52<00:00,  1.31s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:52<00:00,  1.31s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:52<00:00,  1.18s/it]
```

**Comment by Pixl64** [comment]
After looking again at the issues, I think this is the same issue as #81, but leaving this up incase it is something different

**Comment by anapnoe** [comment]
do you have an an issue with the uploaded image or it was only the drop down cutoff I closed this one
issues should contain one subject

**Comment by Pixl64** [comment]
the uploaded image doesn't show either, so I guess that's also an issue

**Comment by anapnoe** [comment]
can you disable canvas-zoom and test again ui-ux has inbuild zoom pan features

**Comment by Pixl64** [comment]
I'll have to do it tomorrow as I don't have access to my PC atm, but I'll do that when I can
