### ISSUE TITLE
[Bug]: Inpainting, sketch related no longer working

### ISSUE THREAD

**Issue by rushuna86** [anapnoe/stable-diffusion-webui-ux#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Sending image to inpaint/sketch/inpaint sketch directly from T2I or importing directly from I2I no longer works.

### Steps to reproduce the problem

1. Go to ....Text2Image generate image
2. Press ....Send to Inpaint
3. Go To Image2Image Inpaint drop/import image.

### What should have happened?

Sends Image to Inpaint or imports imagine to inpaint

### Commit where the problem happens

b00fc0a

### What platforms do you use to access the UI ?

Windows

### Command Line Arguments

```Shell
--xformers --no-half-vae --autolaunch
```

### List of extensions

Tried with Built-in only

### Console logs

```Shell
nothing unusual
```

**Comment by rushuna86** [comment]
Just tried on the previous commit working fine there.

**Comment by rushuna86** [comment]
still broken

**Comment by anapnoe** [comment]
please don't open duplicate issue 
did you update to last commit? `6fbe525`

**Comment by rushuna86** [comment]
yes latest commit, but still exactly the same issue

**Comment by anapnoe** [comment]
can you empty cache and reload the chrome?

**Comment by anapnoe** [comment]
I don't know why this is happening I tested on Chrome, Mozilla, OperaGX, Brave Win10 and it works as it should I will reopen the issue if anyone else can confirm
does this happen from to?
pnginfo > inpaint
txt2img > inpaint
img2img > inpaint

**Comment by anapnoe** [comment]
win10?

**Comment by rushuna86** [comment]
Win 11

**Comment by anapnoe** [comment]
what happens if you drop an image to inpaint does it load correctly?

**Comment by rushuna86** [comment]
hmmmm something is fked, so i did a git pull = broken. i went n did a git clone n did a refresh install from scratch and it works as it should.....

**Comment by anapnoe** [comment]
ok i am glad

**Comment by anapnoe** [comment]
you are welcome
