### ISSUE TITLE
[Bug]: #86 issue still exists

### ISSUE THREAD

**Issue by devioa** [anapnoe/stable-diffusion-webui-ux#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

the issue #86 I opened still exists, and the grid was supposed to display one, but repeatedly displayed.
when I set `Batch count` the each image still missing one to display.
![1](https://user-images.githubusercontent.com/38558065/234738401-7e50d54b-9a71-4ea5-8669-69d9352625d4.png)
but in fact, it is now possible to output 2 images and 1 grid to output directory correctly when I set `Batch count` to 2, which was 2 grids and `Batch count` -1 before.
![2](https://user-images.githubusercontent.com/38558065/234738400-495b6d61-e6b3-4c16-9051-7e4953b60ce8.png)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

grid will display one and the each image will display like I set `Batch count`

### Commit where the problem happens

4b78b6569b960abdc880699ee29f5a01373966f6

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
...
```

### List of extensions

...

### Console logs

```Shell
...
```

**Comment by anapnoe** [comment]
this is strange can you empty the cache and reload in chrome?
![bc](https://user-images.githubusercontent.com/124302297/234821770-53139923-dfa2-4f2b-b0b0-8ad33cad2b0d.png)

**Comment by devioa** [comment]
alright, I found the cause of the issue
I don't remember when I unchecked 'Save grids to a subdirectory'
![2](https://user-images.githubusercontent.com/38558065/234910923-19a9bf89-c830-409a-aae3-b4a2104b70f5.png)
at this point, it will overwrite the last image after the generation is completed
that's why I have the current outcome
after rechecked it, everything goes as planned:
![1](https://user-images.githubusercontent.com/38558065/234911775-0a573827-9427-4ab4-b9a4-1d45e41ce681.png)
![3](https://user-images.githubusercontent.com/38558065/234911784-308e281f-f2fc-4cfd-b1b5-b60e8175b722.png)

**Comment by anapnoe** [comment]
glad that you found the cause best regards
