### ISSUE TITLE
[issue]: ControlNet Image doesn't show

### ISSUE THREAD

**Issue by Pixl64** [anapnoe/stable-diffusion-webui-ux#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Continuation of the issue in #90, but it is slightly separate so I created a new issue

When selecting an image in ControlNet, the image doesn't show, and the 'Start Drawing' text is offset

![image](https://user-images.githubusercontent.com/85389249/234907955-c76bd599-d4f4-497f-b269-fad63f6f06c4.png)

This issue occurs even when all non-built-in extensions are disabled (except ControlNet of course)

Quite often also, it doesn't show the 'Start Drawing' text first attempt, and instead resizes the box and reverts the text to 'Drop image here or click to upload'

**Fresh opening**
![image](https://user-images.githubusercontent.com/85389249/234908587-7fc1360a-3e81-4d92-93bb-032526bcb598.png)

**Selecting image once**
![image](https://user-images.githubusercontent.com/85389249/234908737-aa818fb4-f28e-4c52-9afa-aadf63de2d79.png)

**Selecting image again**
![image](https://user-images.githubusercontent.com/85389249/234908806-192ce15f-c86d-4e8c-bea0-f85c23dc85d8.png)

### Steps to reproduce the problem

1. Install ControlNet
2. Open the ControlNet window
3. Upload an image into the main box

### What should have happened?

The image should show in the box, along with a preview if that setting is selected. It should also appear in the box when selecting it first time.

### Commit where the problem happens

6fbe525f

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--allow-code --administrator --no-half-vae --autolaunch --api --no-download-sd-model --ckpt-dir D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion --vae-dir D:\StableDiffusion\stable-diffusion-webui\models\VAE --lora-dir D:\StableDiffusion\stable-diffusion-webui\models\Lora --embeddings-dir D:\StableDiffusion\stable-diffusion-webui\embeddings --hypernetwork-dir D:\StableDiffusion\stable-diffusion-webui\models\hypernetworks --ui-config-file D:\StableDiffusion\stable-diffusion-webui\ui-config.json
```

### List of extensions

<html>
<body>

sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | 93b0f9e1 (Wed Apr 26 03:16:41 2023) | unknown
-- | -- | -- | --

</body>
</html>

### Console logs

```Shell
Already up to date.
venv "D:\StableDiffusion\stable-diffusion-webui-ux\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 6fbe525f7dafd63b447334b6c476c190b02da7cb
Installing requirements for Web UI

Launching Web UI with arguments: --allow-code --administrator --no-half-vae --autolaunch --api --no-download-sd-model --ckpt-dir D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion --vae-dir D:\StableDiffusion\stable-diffusion-webui\models\VAE --lora-dir D:\StableDiffusion\stable-diffusion-webui\models\Lora --embeddings-dir D:\StableDiffusion\stable-diffusion-webui\embeddings --hypernetwork-dir D:\StableDiffusion\stable-diffusion-webui\models\hypernetworks --ui-config-file D:\StableDiffusion\stable-diffusion-webui\ui-config.json
No module 'xformers'. Proceeding without it.
ControlNet v1.1.112
ControlNet v1.1.112
Loading weights [099e07547a] from D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\darkSushiMixMix_brighterPruned.safetensors
Creating model from config: D:\StableDiffusion\stable-diffusion-webui-ux\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\StableDiffusion\stable-diffusion-webui\models\VAE\orangemix.vae.pt
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(24): bad-hands-5, bad-image-v2-39000, badhandv4, bad_prompt_version2, bad_quality, easynegative, flame_surge_style, guweiz_style, hurybone_style, iskou_style, lightning_style, mikeou_art, nixeu_basic, nixeu_basic2, nixeu_extra, nixeu_soft, nixeu_white, prt, space_style, splash_style, splash_style2, torino_art, vile_prompt3, wano_style_30100
Model loaded in 5.9s (load weights from disk: 0.1s, create model: 0.4s, apply weights to model: 1.8s, apply half(): 0.7s, load VAE: 0.9s, move model to device: 0.8s, load textual inversion embeddings: 1.3s).
D:\StableDiffusion\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
D:\StableDiffusion\stable-diffusion-webui-ux\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 19.9s (import torch: 2.8s, import gradio: 1.6s, import ldm: 0.7s, other imports: 1.5s, setup codeformer: 0.1s, load scripts: 2.3s, load SD checkpoint: 6.0s, create ui: 4.4s, gradio launch: 0.4s).
```

**Comment by anapnoe** [comment]
update sd-webui-controlnet extension
https://github.com/anapnoe/stable-diffusion-webui-ux/issues/91
if you had previous installed canvas-zoom
