### ISSUE TITLE
[Feature Request]: Sidebar Column Selection for Checkpoints, Loras, etc.

### ISSUE THREAD

**Issue by Up-Bound** [anapnoe/stable-diffusion-webui-ux#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hello would you allow us to add a way for us to specify how we allow are grid to show up when we view the sidebar for loras and checkpoints. I have over 200 loras and prefer to view them all on my 1440p monitor in an easily viewable way, for instance allow us to choose an x number of columns and have the size of the previews scale to fit the size of the side window.

### Proposed workflow

1. Go to the webui settings
2. Choose option to select number of columns in Sidebar grid
3. Go to sidebar window for loras, checkpoints, etc.
4. Done.

**Comment by anapnoe** [comment]
hello
go to settings -> extra networks -> Card size for extra networks 
change the slider value to adjust the size

**Comment by Up-Bound** [comment]
Hello @anapnoe thanks for the quick response! Do you know of a way that we can change the font size on the cards for high resolution displays?

**Comment by anapnoe** [comment]
I will add this to theme engine along with the font selection
for now you can use this hotfix in your user.css file
```
.extra-network-cards .card {
    font-size: 120%;
    line-height: 120%;
}
```
